### ISSUE TITLE
No icon load with proxy

### ISSUE THREAD

**Issue by Danieleeee** [janisdd/vscode-edit-csv#1]
Hi,
I'm under proxy and no icon is load:
![1](https://user-images.githubusercontent.com/22749175/54985692-9343a380-4fb1-11e9-9e7b-8c2f7ae26ab2.png)

**Comment by janisdd** [comment]
Ah thanks! It took me some time but i think i found the reason for this...
If i'm correct, it is not related to the proxy but to windows.

I'll try to publish a fix soon

**Comment by Danieleeee** [comment]
Ok, Thanks!

**Comment by janisdd** [comment]
Done. After the update is installed you might need to restart vs code once.
