### ISSUE TITLE
Keyboard Shortcut to delete the current row

### ISSUE THREAD

**Issue by urjeetpatel** [janisdd/vscode-edit-csv#112]
### Version?
- both?

### Feature

There is a current global keyboard shortcut to add a new row / column  but no corresponding keyboard shortcut to delete the current row / column.
Please consider adding a keyboard shortcut to delete the current row

**Comment by janisdd** [comment]
Sure but which keys should be used?

**Comment by urjeetpatel** [comment]
I think it should match the insert rows combination.
so `ctrl+shift+alt+minus`

**Comment by janisdd** [comment]
Im wondering what should happen if an area (more than one row) is selected and this shortcut is used?

- delete only top most row of selection
- delete all rows in selection

Any opinions?

**Comment by urjeetpatel** [comment]
Going from the convention set by excel I think that the expected behavior should be delete all the rows in the selection.

**Comment by janisdd** [comment]
The shortcut will now do the same thing as the context menu action (should do the same thing as excel).

Will ship with next update.
