### ISSUE TITLE
The trash buttons on column and row headers are too easy to be misclicked

### ISSUE THREAD

**Issue by qaqz111** [janisdd/vscode-edit-csv#113]
And then you can hardly know there's data has been deleted by mistake immediately while working with large table filled by similar data in each row/column.

So, can you remove the trash button on headers or just make an option to let the user choose whether to show it directly on headers?

**Comment by janisdd** [comment]
I think options would be better (for columns and rows). But I think by default the buttons should be displayed.

**Comment by qaqz111** [comment]
That would be nice if an option can control this, looking forward to see this function in the next version.

**Comment by janisdd** [comment]
The new settings will be `csv-edit.showDeleteColumnHeaderButton` and `csv-edit.showDeleteRowHeaderButton` (default for both: `true`)

Will be shipped with the next update.
