### ISSUE TITLE
Add newline at the end of file

### ISSUE THREAD

**Issue by qdu-eelab** [janisdd/vscode-edit-csv#115]
### Version?
- vs code plugin

### Feature

- Add option to control whether add newline at the end of file
- Enable (Always keep one newline)
- Disable (Always keep no newline)
- Auto (Detect from origin file)

**Comment by janisdd** [comment]
Di you mean the option `files.insertFinalNewline`? This comes from vs code itself.

**Comment by qdu-eelab** [comment]
I mean if there is newline at the end of origin file, after edit and save by "edit-csv", final newline will lost.

**Comment by janisdd** [comment]
Well, `Enable (Always keep one newline)` and `Disable (Always keep no newline)` can be achieved by the `files.insertFinalNewline` setting.

Why do you need `Auto (Detect from origin file)`?

**Comment by janisdd** [comment]
There is now a new setting `finalNewLine` that can control that... defaults to `sameAsSourceFile`
