### ISSUE TITLE
VSCode sometimes locks workstation when updating (at close of VSCode) but only with this extension enabled. 

### ISSUE THREAD

**Issue by arfyness** [janisdd/vscode-edit-csv#120]
### What OS?
- Windows 10 22H2

### Description
If all the following are true, the workstation locks, sometimes:
- Update on close is enabled
- Edit CSV extension is enabled
- There is a pending update
- VSCode is closed, triggering the update

This is happening on my personal and work computers, both with Win10 22H2.  They have different generation Intel CPUs and different levels (i5, i7) and every hardware item is different on them (Dell vs Lenovo) aside from both using Intel integrated graphics. Even on a very old computer still running Win7 the screen goes to standby (on Win7 it does not lock the computer).

I've narrowed it down only anecdotally, observing this only happens when Edit CSV extension is enabled. I've disabled other extensions, only enabling them when needed, and disabling them otherwise.  I've taken the same practice with this extension, to try to determine the conditions where it locks on me when I quit VSCode.  

The above is my best understanding at the moment, but may have errors.  I'm confused how this happens.

### Expected behavior
Expect the workstation not to lock from closing VSCode with a certain extension enabled.

### Steps to reproduce
- ensure VSCode option to update on close is enabled
- ensure Edit CSV extension is enabled
- ensure there is a pending VSCode update (or could it be Edit CSV update?)
- Close VSCode, triggering the update
- I'm unsure if the computer being locked is a consistent or intermittent outcome.

**Comment by arfyness** [comment]
I'm fully open to some other cause of the locking, such as some other sofware I have on both computers, possibly a driver, possible they intel integrated graphics suite. I have AutoHotKey installed on all affected computers.  For a while I thought it might be consistent that Process Explorer 64 was a common factor so I stopped using it on one device, which, eventually, again got locked from closing VSCode.  It's not a horrible problem, to be fair, but it's a little irritating - moreover it's intriguing and happening on 3 computers, yet I can't find any information online about it at all.  

So, I'm happy to inquire elsewhere, just not sure exactly where to do that. 
Has anyone else seen this happen?  So very very curious.

**Comment by janisdd** [comment]
Hm, here are some questions that come to mind:

- what is update on close? Is this the option `Update: Mode`? `close` is not an option (at least on mac)
- is ist `Win 10 21H2` or `Win10 22H2`? You mention both
- What do you mean by "locks workstation"? Like logging of, so you have to type the password again? Or like the workstation hangs/freezes?
- "when Edit CSV extension is enabled" you mean the table view is open? Or the extension is just activated?
- Are you on vs code insider build? I only get the 1x per month updates, so it might be hard to test
- Have you tried to disable all extensions?

**Comment by arfyness** [comment]
Good questions, thank you.

- It's currently happening on 22H2 but was happening on 21H1 and 21H2 before I updated both computers. I've been ignoring it for a couple years at this point. 
- On all, I have:
"update.mode": "default" 
"extensions.autoCheckUpdates": true
"extensions.autoUpdate": true
- When i say "locks workstation" what I think is happening is that it puts the display in power save mode, which I (maybe?) on Win10 makes windows also lock, similar to WIN+L where password is required to unlock... I say it this way because the old Win7 computer only puts the display to sleep, where no password is required to resume. 
- I am on the standard release channel. And yes it is infrequent enough that it's taken a long time to observe behavior with varoius extensions enabled. Consistently each time, the "whats new" tab is there on the next start of vscode, so I think it happens on app update, as opposed to extension update.
- With extensions disabled, it does not powersave the display or lock windows upon update.
- With the Edit CSV extension disabled, it does not powersave the display or lock windows upon update.
- I want to know for sure but can't test quickly enough - what's the behavior with all other extensions disabled and only Edit CSV enabled, what happens on update then. 
- To that end I will switch to manual update so I have control of which extensions are enabled when I update next time. I hope manual will notify me when one's available.

If no one else is seeing anything like this, I don't know if I care to take a lot of time poking at it, despite my very strong curiosity.

**Comment by janisdd** [comment]
@arfyness how was the latest vs code update? Any changes?

> With the Edit CSV extension disabled, it does not powersave the display or lock windows upon update.

Seems to me that some other extension might be responsible for this?

I also think that it should not be possible for any extension to "control" vs code like this... maybe this issue is better suitable for the vs code repo?

**Comment by janisdd** [comment]
@arfyness any updates?
