### ISSUE TITLE
Clarify TSV is also supported

### ISSUE THREAD

**Issue by tats-u** [janisdd/vscode-edit-csv#121]
### Version?

(at least) VSCode

### Feature

Tables pasted from Excel are converted to TSV (uses tab instead of comma).
It would be nice if how to edit TSV is written in README.

(AVIF; required a browser other than Safari)

https://user-images.githubusercontent.com/12870451/235279596-6d2426de-0ed9-4181-9cd4-ab82a9692b99.mp4

**Comment by janisdd** [comment]
>It would be nice if this extension supports direct edit of TSV without having to convert them to CSV.

What do you mean by that? It works for `.tsv` files.

Yan can copy and past from/to excel.

Can you give more details?

**Comment by tats-u** [comment]
1. Change the language mode to TSV
2. Start "CSV: edit csv"

**Comment by tats-u** [comment]
Sorry it has already been supported.
I forgot to change the indent from space to tab.

https://user-images.githubusercontent.com/12870451/235279596-6d2426de-0ed9-4181-9cd4-ab82a9692b99.mp4

**Comment by janisdd** [comment]
Using "new file" is different than using an existing file. On an existing `.tsv` file it works as expected. Using tabs for `tsv` is required (hence the name).

Actually it would work with almost any delimiter (can be configured). However, the button (and action) will only work on known languages (`csv`, `tsv`). This has nothing to do with the extension ifself, but how vs code handles languages.

However, I'll add a sentence to the readme on how to edit new files as tsv.
