### ISSUE TITLE
How to customize text color?

### ISSUE THREAD

**Issue by aoyama-val** [janisdd/vscode-edit-csv#122]
### What OS?
- Mac

### Description
I have looked for the way to change the table's text color, but didn't find one.
Is this possible?
The default color is too light for my light background.

**Comment by janisdd** [comment]
This is currently not possible. Would the text color have to change the text of controls (buttons, ...) too?

**Comment by aoyama-val** [comment]
It might be helpful for some people, but I do not feel the need to do so. The effort to customize it would outweigh the benefits.
![image](https://github.com/janisdd/vscode-edit-csv/assets/13144822/7535bb6c-11ee-4e10-be1b-17e60b6547cf)

**Comment by janisdd** [comment]
I've added options to change the table text color `darkThemeTextColor` and `lightThemeTextColor`. Lets see if this is enough.

Will be released with the next update.

**Comment by janisdd** [comment]
Additional note: Any valid css color will work. When the color is invalid, the default color is used.
