### ISSUE TITLE
Edit csv button not displayed

### ISSUE THREAD

**Issue by aoyama-val** [janisdd/vscode-edit-csv#123]
### What OS?
- Mac

### Description
"Edit csv" button is not displayed. The filetype is CSV.
![スクリーンショット 2023-05-22 10 33 05](https://github.com/janisdd/vscode-edit-csv/assets/13144822/66b11dba-c515-4a51-8e0c-72e96d81e23b)

### Steps to reproduce
Just open this [sample.csv](https://github.com/janisdd/vscode-edit-csv/files/11526142/sample.csv).

**Comment by janisdd** [comment]
Have you installed the extension? Or is it disabled?

Does it work with other files?

**Comment by janisdd** [comment]
Do you use the insider version or github.dev or something special? Or do you have the `.csv` file extension mapped to a different file type (search in settings for `associations` and look for `Files: Associations`)?

**Comment by aoyama-val** [comment]
Ah, I don't know where this came from, but it was there:

```
    "csv-edit.hideOpenCsvEditorUiActions": false,
```

Sorry for the trouble, closing the issue.
