### ISSUE TITLE
The unsaved indicator should only appear if there are unsaved changed

### ISSUE THREAD

**Issue by RamblingRyan** [janisdd/vscode-edit-csv#127]
### What OS?
- Windows

### Description
When Edit CSV is opened, the unsaved indicator (asterisk in tab) appears all the time, even for very small simple correctly constructed CSV files.

### Expected behavior
No unsaved indicator unless there are unsaved changes

### Steps to reproduce
Open a CSV file. Click 'Edit CSV'. 

### Note
Thanks for excellent extension. Really appreciate it.

**Comment by RamblingRyan** [comment]
Tested for this issue on a fresh installation of VSCode and Edit CSV, and the problem didn't happen, so I guess it can be closed. Not sure why it was happening on the other machine.

**Comment by janisdd** [comment]
The indicator *should* work fine. It may happen that it is displayed immediately after opening the table, because
- not all rows have the same number of cells (missing ones are inserted)
- empty lines (no fields) are removed
- maybe a few others that I can't think of at the moment
