### ISSUE TITLE
can dev add toggle word-wrap?

### ISSUE THREAD

**Issue by lzygitk7** [janisdd/vscode-edit-csv#128]
### Version?
- vs code plugin
- browser
- both?

### Feature

Describe the feature you want to suggest.

**Comment by janisdd** [comment]
Not 100% sure what you mean but there is an option `csv-edit.enableWrapping` that wraps cells.

**Comment by janisdd** [comment]
@lzygitk7 is `csv-edit.enableWrapping` the feature you described?

**Comment by lzygitk7** [comment]
Sorry for delay reply. Not really, but thank you for your reply.

Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by janisdd** [comment]
So what do you mean by word-wrap then? Or how it is different from the current functionality of `csv-edit.enableWrapping`?

**Comment by janisdd** [comment]
You know the cell is only wrapped if you change the column size manually... by default the cell will auto size to fit the content on a single line.

You could set `csv-edit.initialColumnWidth` to a small value and see the wrapping immediately.

**Comment by janisdd** [comment]
@lzygitk7 Can this be closed? You have to manually resize the column first. How should the table know which width is the best? For this reason, the initial width is adjusted to the contents of the cell.
