### ISSUE TITLE
add support for different encoding

### ISSUE THREAD

**Issue by chaeynz** [janisdd/vscode-edit-csv#135]
### Version?
Id: janisdd.vscode-edit-csv
Version: 0.8.3

### Feature

Describe the feature you want to suggest.

Hi there! I love your extension.

Any chance you can add support for different encodings?
I can't display german "Umlaut" characters. It's not absolutely necessary, but it confuses my stakeholders.

![image](https://github.com/janisdd/vscode-edit-csv/assets/97678748/ed5dc440-9e69-466b-bbd2-c98f48472791)

The encoding that I specifically work with is Windows CP 1252 ([Windows-1252](https://en.wikipedia.org/wiki/Windows-1252))

**Comment by janisdd** [comment]
Well, the encoding is handled by vs code. This means everything *should* work out of the box.

![csv_windows_enc](https://github.com/janisdd/vscode-edit-csv/assets/12775963/f8e904f2-af60-4b2b-be9b-732f39e67e0d)

I tested it by creating a new file and clicked on the red rectangle and changed from utf8 to windows 1252 (save with encoding). As you can see, it works ;)

It does not work, if the file is windows 1252 encoded and vs code opens it with utf8 encoding (see red rectangle). If so, click on the rectangle and choose "reopen with encoding".
The same can happen if the real encoding is utf8 and the editor opens it with windows 1252 encoding.

**Comment by chaeynz** [comment]
You are absolutely correct! haha
Sorry, my mistake! 😆
