### ISSUE TITLE
text search takes long time.

### ISSUE THREAD

**Issue by mortunco** [janisdd/vscode-edit-csv#138]
### What OS?
- local computer is Mac but using remote-ssh vscode) Amazon Linux2

### Description
I have a document 1500 rows x 26 columns. Ist a datatable only one column have 500 characters. I wouldnt call this necessarily bug sometimes but search is taking so much time whereas other times it gives instant result. Same search is still instant when i open the csv with editor. 

### Expected behavior
I think it should be instant with this size of the document.

### Steps to reproduce
I cant reproduce it effectively.

### Maybe helps
1) This file is in Amazon EFS so my one guess is when someone else is doing IO heavy jobs maybe locks it. Could you maybe help me to monitor this? Like which console I should check then this long searches are happening?

Thank you very much for developing this tool. This is making my life very easy and its realiable.

Best,
T.

**Comment by janisdd** [comment]
Glad you like it so far.

First of all, what is long? 1s, 10s, 1 minute?
And do all your columns have 500 chars? Or only some or all?

I have tested locally with 100 000 rows, 14 columns and it takes 4/5s.
The search does not access the disk, but only the memory.

Maybe the vm is low on memory and swapping?
And what does the user interface look like? The search has a progress bar, does it fill up slowly or does it fill up and the display of results is delayed?

**Comment by mortunco** [comment]
Okay. I can answer these questions.

_First of all, what is long? 1s, 10s, 1 minute?_
10s + seconds maybe 30. No more than 1 minute.

_And do all your columns have 500 chars? Or only some or all?_
Definetely no. Some cells in the colums are long query links. Some of them are 10 char string.

_Maybe the vm is low on memory and swapping? An what does the user interface look like? The search has a progress bar, does it fill up slowly or does it fill up and the display of results is delayed?_
UI is responsive. The ideal case is instant. My problematic case, progressing slowly. its not jumping in 20-30% jumps. but rather steadily going up. (for instance today is not happening). I will check next time happens and report here htop output for memory/swap. Feel free to close this, i will reopen with the new data.. I would definitely report this here.

**Comment by mortunco** [comment]
dear @janisdd 

I had the problem yesterday. This is the screen from the htop sorted by the memory. the only striking thing i see is the VIRT column of the vscode remote server. 

![Screenshot 2024-01-31 at 4 30 15 PM](https://github.com/janisdd/vscode-edit-csv/assets/12833865/186f1e7f-41d2-4ded-a6a9-17bf6d881042)

Should I check any of the other logs in the vscode side?

Best,
T.

**Comment by janisdd** [comment]
In the next update I'll add some timing measurements for the search. You can then look at the console (command palette: >Developers: Toggle Developer Tools) to see some timing data.
