### ISSUE TITLE
Switching tabs with number keys clears active cell

### ISSUE THREAD

**Issue by ChillerDragon** [janisdd/vscode-edit-csv#139]
### What OS?
- Linux

### Description
Pressing option/alt + number clears the currently selected cell.
I press alt+1 constantly to switch to my first tab in vscode. And everytime it clears the current cell.

https://github.com/janisdd/vscode-edit-csv/assets/20344300/ada38ad8-9b64-4913-92da-e748a37b1499

### Expected behavior
I expect switching tabs to not alter the spreadsheet data

### Steps to reproduce
select a cell with content. Switch tabs using one of those hotkeys
![image](https://github.com/janisdd/vscode-edit-csv/assets/20344300/187bbd82-9a13-4010-84a3-31a70f3a8b6f)

**Comment by janisdd** [comment]
On mac, the shortcut is `ctrl+x`, so I'm only adding this only for windows/linux.

When I press `alt+3` (on mac) I get `¶` (changed my keyboard layout).

Can you please open a text editor (gedit and maybe another one to be sure) and press `alt+1`, `alt+2`, ..., `alt+9` and check if some character is printed?

On windows it seems to print no character but use the program menu.

**Comment by ChillerDragon** [comment]
On debian + gnome alt+number does not insert characters in gedit/browsers/vim. Things of course change if you start configuring your compose key to be alt.
