### ISSUE TITLE
EditCsv interprets all lines as comments if Read Options > Comment is blank

### ISSUE THREAD

**Issue by Nu11u5** [janisdd/vscode-edit-csv#14]
When opening a csv file with EditCsv the table will display all data as comments.  The Read Options > "Comment" field is blank.  The "Has Header" toggle is enabled but does not change when clicked.  The "Delimiter" field tooltip says "auto - (detected: ,)" which is correct for my file content.

If I enter a character into the "Comment" field (such as "#") and click "Reset Data" the csv file will load into the table correctly and I can toggle "Has Header" on.

If I close the EditCsv editor tab and reopen the csv file with it, the Read Options are reset and the above process must be repeated to correctly load the csv file into the table.

I have tested disabling all other extensions and reloading VSCode and EditCsv still shows the same behavior.

---

VSCode:

Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.14393

EditCsv:

Name: Edit csv
Id: janisdd.vscode-edit-csv
Description: extension to edit csv files with a table ui
Version: 0.1.4
Publisher: janisdd
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv

**Comment by janisdd** [comment]
>When opening a csv file with EditCsv the table will display all data as comments.

You set the setting `Csv-edit: Write Option_comment` to empty, right?

So the issue here is that with an empty "Comment" field the table should treat all rows as actual data?

And just because I'm curious, why would you set "Comments" to be empty? Is there a real use case?

**Comment by janisdd** [comment]
Maybe extension version 2.2 fixed this issue?

**Comment by Nu11u5** [comment]
Yes it is fixed now!
