### ISSUE TITLE
Hide a column

### ISSUE THREAD

**Issue by 52fisher** [janisdd/vscode-edit-csv#140]
### Version?
both

### Feature
Hello developer, thanks for developing this great plugin. I use this plugin mainly to provide Chinese translation for some good mods, there are some columns in other languages, and I just need some of them to be enough, if all the columns come out, it will look like this page is especially crowded, making it difficult to read. I hope to add the ability to hide a certain column.
![图片](https://github.com/janisdd/vscode-edit-csv/assets/32198215/7ce214f8-b68c-43b7-8c31-6c4d4080aaa1)

Describe the feature you want to suggest.

**Comment by janisdd** [comment]
Interesting idea! I think this would is possible because hiding rows with comments also works.

It would be best to add the following two options to the context menu (right-click):
- hide/unhide column
- hide/unhide row

I'll look into this

**Comment by janisdd** [comment]
To keep things simple, I only implemented the "hide column" feature (was more work than expected, so no "hide rows").

It also supports selecting multiple columns (cells) and hiding them with one click.

Will be part of the next update.

**Comment by 52fisher** [comment]
Thank you, janisdd. this is really good news.

**Comment by janisdd** [comment]
Before I forget, for the documentation: unhiding columns sets the column widths to automatic size

**Comment by 52fisher** [comment]
BTW, this extension is really so excellent that I would like to share it to more friends. I don't know if you have any plan to do localization (by vscode-nls) for this extension, I'm willing to contribute Chinese translation!

**Comment by janisdd** [comment]
Thanks for the offer, but I currently have no plans to add localization.
I don't think there is much text in the extension and it would make the extension more complicated (with little benefit).

By the way: The next update is expected to be released this weekend.
