### ISSUE TITLE
CSV data is split in an unexpected way. 

### ISSUE THREAD

**Issue by ruanluyu** [janisdd/vscode-edit-csv#141]
### What OS?
- Windows

### Description

![data](https://github.com/janisdd/vscode-edit-csv/assets/17758186/7a5b660f-48b0-43d5-bd4b-98daa011a758)

![data_displayed](https://github.com/janisdd/vscode-edit-csv/assets/17758186/eac76644-1e03-449d-9f7e-241b733cfd28)

### Expected behavior

Data should be split by comma. 

### Steps to reproduce
Download this csv data. 
[map_extra.csv](https://github.com/janisdd/vscode-edit-csv/files/14163630/map_extra.csv)
Open it via VSCode. 
Click "Edit csv" button.

**Comment by janisdd** [comment]
Well, I count 3 commas per line but 4 `.` per line --> `.` seems to be the better guess.

You can set the separator (`delimiter`) manually under `Read options` (then click on `Reset data and apply read options`).

**Comment by janisdd** [comment]
I guess this can be closed
