### ISSUE TITLE
[Feature Request] Add option to automatically update the table on source file changed

### ISSUE THREAD

**Issue by urjeetpatel** [janisdd/vscode-edit-csv#147]
### Version?
- vs code plugin

### Feature

There is an configurable option that will watch the source file for changes and will prompt the user to refresh to update the table.
Can another configuration be added to this so that the table gets automatically refreshed on source file changes? This can default to false to have the existing behavior but for my use case i would love to have the parsed csv table interface automatically update as the source file changes. 

Maybe have the option next to this in the settings.
![image](https://github.com/janisdd/vscode-edit-csv/assets/1077440/5bb1fe0f-0d34-4ce3-a019-486259c71b26)

and have the title be `Automatically reload table on source file change`.

**Comment by janisdd** [comment]
Do you use the table to display data or do you also edit it?

This can be important, as reloading the file means that all changes made to the table will be discarded.

**Comment by urjeetpatel** [comment]
I use it for both editing and for displaying data.
However I would still like to have the option to automatically refresh the table even if it overwrites any edits made.

This is why it should be user configured and allow people to make the decision if they want their changes overwritten or not.

**Comment by janisdd** [comment]
I've changed the `shouldWatchCsvSourceFile` option to be an enum:

- `no`: do not watch the source csv file for changes
- `yesAndNotify`: the source csv file is watched for changes and you will be notified if the source file is changed
- `yesAndAutoReload`: the source csv file is watched for changes and new data is automatically loaded, overwriting existing changes (no undo!)

Will ship with the next update
