### ISSUE TITLE
Suggestions...

### ISSUE THREAD

**Issue by ToxicLand** [janisdd/vscode-edit-csv#156]
### Version?
- vs code plugin 0.9.1

### Feature

Describe the feature you want to suggest.

I'm not sure if any of these features are configurable, but I haven't found anything related to them:
-Ability to ctrl+z if I press on the header title by accident (or a way to disable sorting by clicking on it)
-When I paste a new row, I don't want the program to auto scroll to the last column
-When I insert a new empty row and select it, let's say I want to paste a few new rows from another csv file, I want to paste them without overwriting the rows below the empty line.
-When I ctrl+a ctrl+c, I want the header to be copied as well (it helps a lot when I do a text comparison)

Bonus: Not sure if this is a bug, but the Edit csv button is not visible for some csv files. Attached example.
[chat_rules.csv](https://github.com/user-attachments/files/16091091/chat_rules.csv)

**Comment by janisdd** [comment]
Your `chat_rules.csv` files works just fine for me. Make sure that `CSV` is specified as the language mode in the bottom right-hand corner. Maybe some other extension is changing the file language to be something other than csv?

> Ability to ctrl+z if I press on the header title by accident (or a way to disable sorting by clicking on it)

Why ctrl+z? Click twice more on the header and the sorting will be undone.

> When I paste a new row, I don't want the program to auto scroll to the last column

What it should do instead?

> When I insert a new empty row and select it, let's say I want to paste a few new rows from another csv file, I want to paste them without overwriting the rows below the empty line.

If I'm not mistaken, the current behavior is the same as in Excel. However, I understand that a true *insert* can sometimes be useful. Maybe a setting or a new entry in the context menu for cells.

> When I ctrl+a ctrl+c, I want the header to be copied as well (it helps a lot when I do a text comparison)

I suggest not using a header and instead freezing/fixing the first column (3rd icon from the right).

**Comment by ToxicLand** [comment]
Thanks for the response! You are right, for some reason it wasn't detected as a CSV.

> Why ctrl+z? Click twice more on the header and the sorting will be undone.
I didn't know about it, works perfectly now.

> What it should do instead?
Stay at the currently active/selected row. I'm coming from Windows (Ron's Editor) and this behaviour is slightly annoying. It also glitches at the last line, keeps scrolling up/down by 1 line and when I select the last row, 2 gets selected instead and it jumps to the end of the row where I don't see the text. Here is a video: [https://streamable.com/4prrg2](url)

> If I'm not mistaken, the current behavior is the same as in Excel. However, I understand that a true insert can sometimes be useful. Maybe a setting or a new entry in the context menu for cells.
Please consider adding this. I use it a lot and I have to manually create empty lines when I want to paste something.

**Comment by janisdd** [comment]
I can't really do anything about the "glitching", it's a problem with handsontable (library used for the table). It only occurs when the cells are very long (and may have something to do with wrapping).

I will look into the pasting behavior.

**Comment by janisdd** [comment]
There will be two new options:

- `pasteBehavior` (can be used to move cells instead of overwriting)
- `pasteScrollBehavior` (can be used to disable scrolling to the pasted cells)


New cells can now also be created when pasting.
