### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by srfrnk** [janisdd/vscode-edit-csv#158]
### What OS?
- Mac

### Description
When opening a CSV getting the following messages:

- Could not find option: initiallyHiddenColumnNumbers in csv-edit configuration
- Could not find option: dragToAutoFill in csv-edit configuration

### Expected behavior
No error messags

What you'd expect to happen.

### Steps to reproduce
A step by step guide how to reproduce this issue/bug.

**Comment by janisdd** [comment]
I'm not sure what you did, but it works for me on multiple machines.
I forgot the defaults for `initiallyHiddenColumnNames` and `initiallyHiddenColumnNumbers` but `dragToAutoFill` should have to default `none`.

What do you see when you go to vs code `Settings` and search for `initiallyHiddenColumnNumbers`, `initiallyHiddenColumnNames` and `dragToAutoFill`, are there any values?

**Comment by srfrnk** [comment]
As you can see here these values do not appear in my settings file:
![image](https://github.com/user-attachments/assets/7750aa1e-c75a-4364-9d99-85d301a52627)

This is a capture of the error messages:
<img width="569" alt="image" src="https://github.com/user-attachments/assets/cccdf111-ac8a-47d5-9c96-799ba7aef125">

If I try to set values it seems vscode doesn't know these:
<img width="593" alt="image" src="https://github.com/user-attachments/assets/d4f97d14-c650-4342-b88b-b85a8084d672">

**Comment by janisdd** [comment]
Do me a favor and open the settings via ui (cmd + ,) and search for `initiallyHiddenColumnNames` or just `initially`. Are the options `initiallyHiddenColumnNames` or `initiallyHiddenColumnNumbers` displayed?

What is your vs code and extension version?

**Comment by srfrnk** [comment]
They seem to show here but don't have any values: 
<img width="1240" alt="image" src="https://github.com/user-attachments/assets/9bdbbfce-be36-47af-a73a-b62356a2b9e8">

**Comment by janisdd** [comment]
They should have no values by default. In the next version, I'll set the empty array as the default. However, it works on all my machines without an explicit default. 
But maybe you can add an element and remove it again?

By the way, have you tried reinstalling the extension?

**Comment by srfrnk** [comment]
Thanks @janisdd for some reason I can't reproduce this issue now.
It was happening every time I use the plugin but now just doesn't ever.
I'm happy with that "solution" so I'll close this now.
