### ISSUE TITLE
CSV-Files larger 50MB not supported by extension

### ISSUE THREAD

**Issue by wrogner** [janisdd/vscode-edit-csv#159]
### What OS?
- Mac

### Description
csv-file with 210MB (on disk) cannot be edited by edit-csv
(switch to edit csv view -> Error: Open a csv file first to show the csv editor or file too large (> 50MB)

### Expected behavior

Open csv-file
switch to edit csv
-> see the grid and editing mask

### Steps to reproduce
open any csv-file larger than 50 MB

**Comment by janisdd** [comment]
This is a vs code extension limit, see https://github.com/janisdd/vscode-edit-csv/issues/88
