### ISSUE TITLE
can I fix the first row when scrolling the content?

### ISSUE THREAD

**Issue by oceancx** [janisdd/vscode-edit-csv#16]
the first row's infomation can help me know what i am editing, in my opinion , making it fixed when scrolling is very important.

**Comment by janisdd** [comment]
The header row doesn't fit your needs (read options > has header)?

Actually I'm not a fan of the header row because it's not editable and with the last update changing the `has header` option will clear undo/redo

So I guess a new extension setting to fix the first X rows would be a good solution?

**Comment by janisdd** [comment]
After some testing it seems that we need to make `has header` and `fixed Rows` mutually exclusive (`has header` has priority)

**Comment by oceancx** [comment]
sorry, i didn't notice there is a has header option, that's what i want.

**Comment by janisdd** [comment]
Ok but keep in mind you can't edit the header row and when you toggle the `has header` option the undo/redo is cleared
