### ISSUE TITLE
The command to open a CSV file isn't properly capitalized

### ISSUE THREAD

**Issue by tudortimi** [janisdd/vscode-edit-csv#164]
### Description
The command to edit a CSV file is called "Edit csv" (with CSV in lowercase).

### Expected behavior
Proper capitalization would be to use uppercase for the acronym. The command would be called "Edit CSV".

**Comment by tudortimi** [comment]
This is a nitpick on my part, but it would make the UI more consistent with VS Code in general, which capitalizes words in command names.

**Comment by janisdd** [comment]
Why not
