### ISSUE TITLE
sometimes, some cells are too long over a screen width, others are normal, but the column is expaned to the longest width in one line.

### ISSUE THREAD

**Issue by oceancx** [janisdd/vscode-edit-csv#17]
is there a cell width limit that i can set to have a better view for my tsv files or the cell can take place multilines, or just collapse the long cell and expand it when edit?

**Comment by janisdd** [comment]
This should be `csv-edit.initialColumnWidth`.
You can see a full list of options if you search for `csv-edit` in the settings or when you goto the installed extension and open this extension (in vs code) and click on the `Contributions`.

I think it also works together with `csv-edit.enableWrapping`

**Comment by oceancx** [comment]
thanks for your tips, I just became lazy...
