### ISSUE TITLE
release also vsix extension file

### ISSUE THREAD

**Issue by mirekphd** [janisdd/vscode-edit-csv#20]
Could you release the .vsix extension here on Github? For a good practice please consult this repo:
https://github.com/Azure/vscode-kubernetes-tools/releases

**Comment by janisdd** [comment]
Yeah sure, starting from the next release I'll provide the .vsix here too.

I'm curious, why don't you use the store .vsix download link? Is there an advantage to provide it here on Github?

**Comment by mirekphd** [comment]
Excellent! We were missing this type of tool in our Linux containers.

The advantages of GitHub over marketplace are visible in our use case of
automated builds designed for an offline environment. The biggest of them
is probably automated extensions  updating made possible by the ability to
find the latest tag or release without resorting to selenium:)

**Comment by janisdd** [comment]
Ah thanks for the explanation. I've never thought about that kind of issue ;)

I'll close this after the next release (as a reminder)

**Comment by janisdd** [comment]
@mirekphd can you check if your automated extension update thing is working?
