### ISSUE TITLE
Pasting text into search field does not work using the keyboard shortcut under MacOS

### ISSUE THREAD

**Issue by MinesService** [janisdd/vscode-edit-csv#21]
I really love the addon. Unfortunately, If I use the search field, it is not possible to paste text into the search field using the key combination ⌘ + v on MacOS.

Visual Studio Code: 1.42.1
Edit csv: 0.2.5
MacOS: 10.15.3

**Comment by janisdd** [comment]
Hm... I can confirm this issue. Windows seems to work fine.
I'll look into this.

**Comment by janisdd** [comment]
I think it should be working now
