### ISSUE TITLE
Scrolling behaviour when Shift is pressed

### ISSUE THREAD

**Issue by k6b2yjxma7li** [janisdd/vscode-edit-csv#23]
Most editor views support scrolling up and down as a default mouse roller behaviour and additionally change that to horizontal scrolling when `Shift` is held. I've noticed that _Edit csv_'s table view does not support that, at the same time horizontal scrolling with touchpad is possible. I would like to see this as a feature.

**Comment by janisdd** [comment]
So you say `shift` + scrolling is **not** scrolling horizontally for you?

I tested that on mac and windows (7) and it's working for me.

**Comment by k6b2yjxma7li** [comment]
So it's on my side, huh? Bad luck to be me. Yeah, it is not working. My OS is Win10 and I have tried different mouses also (mine is connected via BT, so did it to be sure that's not the source of the problem). At this point I was looking for some workaround, but found none.

To be double sure I tested this with all but _Edit csv_ extensions disabled. Unfortunately nothing changed. I hope we could figure out what is the problem, because I am using your extension on daily basis and I like it very much.

**Comment by janisdd** [comment]
Can you please go to https://handsontable.com/docs/6.2.2/demo-scrolling.html and check if you can scroll horizontally with `shift` there?

I also checked with win10 and it's also working there.

**Comment by k6b2yjxma7li** [comment]
It does not work on the provided example. Now I'm really curious about what is going on.

**Comment by janisdd** [comment]
Well I'm using an old version of handsontable... You can check the latest version of the example here https://handsontable.com/docs/7.4.2/demo-scrolling.html

If it's still not working for you it is probably an issue with the library itself and you can open an issue on the handsontable repo https://github.com/handsontable/handsontable

**Comment by k6b2yjxma7li** [comment]
Yup, same story with this second example. I'll follow your advice and try finding some answers on their repo. Thank you.
