### ISSUE TITLE
How to change the delimiter for an open file?

### ISSUE THREAD

**Issue by elpres** [janisdd/vscode-edit-csv#24]
I've opened a .tsv file, and the extension seemed to have picked comma as the separator, which of course isn't the right one since it's a "tab separated values" file. So then I opened up the top bar ("Read options", "Write options", "Preview", etc.) and selected "tab" as separator by clicking the icon next to "Delimiter". The tab character is inserted into the box below, but clicking "Apply" doesn't change the display of the table. This seems like the correct procedure, right?

**Comment by janisdd** [comment]
Actually `Apply` is used to apply the changes back to the file. To apply the new read options you need to click on `Rest data`. You can hover over the `?` to get help for the buttons.

Now that I'm thinking of it... the names of the buttons might be misleading. I'll rename them to something more meaningful.

**Comment by elpres** [comment]
Okay, thanks for clearing that up. "Reset data" made me think of destroying all data, so I avoided clicking it :)

Yeah, maybe something like "Reload" or "Reread" would be more self-explanatory.

Anyway, thanks for making the extension, it's very useful.
