### ISSUE TITLE
Applying and saving file when pressing ctrl+s

### ISSUE THREAD

**Issue by d2verb** [janisdd/vscode-edit-csv#26]
It will make this extension more convenient I think.

**Comment by janisdd** [comment]
I agree. Would be useful.

**Comment by janisdd** [comment]
Fixed in 6329d3b3eb7ef348c1dc2c61f7f03d12858927a9

**Comment by d2verb** [comment]
Thanks!

**Comment by janisdd** [comment]
Will shipped with the next update
