### ISSUE TITLE
Just dissapear the button to edit csv

### ISSUE THREAD

**Issue by ZurMaD** [janisdd/vscode-edit-csv#27]
Hello, the button to edit the csv just dissapears

![image](https://user-images.githubusercontent.com/28235457/82581696-91925300-9b56-11ea-859d-bc4f7810873f.png)

**Comment by janisdd** [comment]
This might be related with the latest update... What vs code version are you using? You are on windows (10)?

**Comment by ZurMaD** [comment]
Sorry, I think it was a configuration on my visual studio. Sorry for the mistake

**Comment by janisdd** [comment]
In the first screenshot I see in the lower right corner it says "plain text" but it should be "csv"... Does it say "plain text" for the other csv files?

**Comment by ZurMaD** [comment]
Yes, it's detected as plain text also for me.  No, I'm just having problems with this specific file. 
Might be some error in the csv file?

**Comment by ZurMaD** [comment]
![image](https://user-images.githubusercontent.com/28235457/82584113-a3c1c080-9b59-11ea-856b-46025e29adb0.png)
Why is vscode opening with a `utf-8` modified version like `utf-8 with BOM`

**Comment by janisdd** [comment]
Hm, I tried with and without utf8 BOM, CRLF/LF and the content you posted... But in all cases the file is recognized as csv file not as plain text. The file type is determined by vs code not by the extension.

**Comment by ZurMaD** [comment]
This is weird because I moved the file to another folder and it works ¿?

**Comment by ZurMaD** [comment]
Okey that was really weird, I moved to the initial folder and it's working 

![image](https://user-images.githubusercontent.com/28235457/82585936-70ccfc00-9b5c-11ea-9264-0fbfcbb0c463.png)

**Comment by janisdd** [comment]
Absolutely NO idea :disappointed_relieved:

**Comment by ZurMaD** [comment]
I changed the name of the folder from `templates` I think VSCODE do something in folders called `templates`. I will create an Issue for vscode. I think it's not an Issue for extension:vscode-edit-csv and it's time to close the Issue.
