### ISSUE TITLE
Ability to add more extension types

### ISSUE THREAD

**Issue by attempted** [janisdd/vscode-edit-csv#28]
I use the extension "Rainbow CSV", which adds some custom Language Mode types into VSCode, i.e. `CSV (pipe)`. When swapping from `CSV` to `CSV (pipe)`, the "Edit as csv" ability disappears. Would it be possible to add a setting where we could add additional Language modes?

![image](https://user-images.githubusercontent.com/29066530/82708380-1c08ae80-9c4c-11ea-8434-563d49324101.png)

**Comment by janisdd** [comment]
I don't think this is possible... I need to set the language names hard coded in the package.json.
It looks like this:

```json
{
  "when": "editorLangId == csv",
  "command": "edit-csv.edit",
  "group": "navigation"
},
```
and you cannot use js inside "when" (as for as I can tell).

When I look into the "Rainbow CSV" extension package.json I only see "csv (pipe)" as a missing language (maybe the others come from other extensions?).

The only way to solve this would be to hard code all language ids (from the img above) in this extensions package.json.

What do you think?

**Comment by attempted** [comment]
They're all from Rainbow CSV, I tested removing the extension and and all of those extensions in the screenshot were also removed. Seems like a hassle just to enable compatibility with one extension, so I'll continue swapping back to the standard `CSV` language mode when I need to edit. Thank you!

**Comment by janisdd** [comment]
Nah, it should be pretty easy to add these modes. Just to be sure, you need to manually switch to e.g. CSV (pipe) or does Rainbow CSV/vscode automatically selects this when you open a file that is pipe delimited?

I'll add the modes in the image next weekend (probably). Probably there are other that have the same problem but didn't create an issue ;)

**Comment by attempted** [comment]
There's an option in Rainbow CSV that will swap automatically when it detects a delimiter type that you've configured. If it's not in the list it'll keep the Language Mode as standard `CSV`. Thank you!!

![image](https://user-images.githubusercontent.com/29066530/83381354-72918d80-a3ae-11ea-871b-bdfdc08021c7.png)

**Comment by janisdd** [comment]
Ah ok, didn't know about this. So I'll not touch the list of supported language modes and close this. 
Thanks for the investigation!
