### ISSUE TITLE
Add Option to change the Column names to match like Excel

### ISSUE THREAD

**Issue by violentmagician** [janisdd/vscode-edit-csv#29]
I am using your extension a lot to reconcile data between CSV files and Excel Worksheets.
It would be a really nice feature to have the ability to show the column numbers like in Excel with letters A-ZZZ instead of Column Numbers.

Is this something that you would be open to adding?

**Comment by janisdd** [comment]
In fact handsontable displays the column names like excel by default and I had to change that.
It should be possible to add an option for that. I'll have a look (probably this weekend).

**Comment by janisdd** [comment]
I've added an option `showColumnHeaderNamesWithLettersLikeExcel` which can be set to true to change the column names to letters.

**Comment by violentmagician** [comment]
Thanks for the Enhancement.
