### ISSUE TITLE
Unable to use vscode default shortcut to switch between editors

### ISSUE THREAD

**Issue by bcardiff** [janisdd/vscode-edit-csv#31]
First of all, thanks for this extension!
I notice an issue with the navigation between editors if the current one is edit-csv.

Since Cmd+Opt+Left and Cmd+Opt+Right are used to select from the current position to the beginning and end of the current row I cannot switch among editors using those shortcuts if the current editor is edit-csv.

It seems that the shortcut for the row selection in this extension is not configurable and I would rather prefer to change the shortcut of changing the editor. 

If the shortcut itself is not configurable in handsontable maybe it could be disabled by a configuration. Would that make sense?

**Comment by janisdd** [comment]
The whole shortcut thing is a bit tricky. I have no idea what and how many handsontable assigns by default (probably also depending on the OS). I'm also not sure if anyone actually uses the shortcut to edit the table... disabling it for handsontable in the config might be a good idea.

I'll look into this and try to come up with something that works well for mac/win/linux shortcuts.

**Comment by janisdd** [comment]
I tried some stuff but nothing worked...
Think this cannot be fixed atm, I opened an issue here https://github.com/microsoft/vscode/issues/101750

**Comment by bcardiff** [comment]
Thanks for trying and escalating it

**Comment by rcaught** [comment]
Same for ctrl+tab (just for documentation 😄)

**Comment by janisdd** [comment]
After *just* ~2,5 years this will be fixed... See #139

I'll add an exception for `ctrl+tab` and `ctrl+shift+tab`.

However, this is hard-coded and does not change if you change the key assignment in the vs code.

**Comment by bcardiff** [comment]
Thank you! I think it's still valuable even if hardcoded.
