### ISSUE TITLE
Won't it be best if "Edit csv", "Excel Viewer" and "Rainbow CSV" are merged (Keeping the best of each in one and adding extra features in a single extension)?

### ISSUE THREAD

**Issue by mesajidiqbal** [janisdd/vscode-edit-csv#32]
https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv
https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer
https://marketplace.visualstudio.com/items?itemName=mechatroner.rainbow-csv

**Comment by janisdd** [comment]
In my opinion no. Here are the reasons/concerns:

- this extension is focused on csv (view and edit) only
- why merge with Excel Viewer and not e.g. Data Preview (https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview)?
- I also thought on supporting Excel files... but I like the idea of "one extension for one job" (something like that)
  - when the merged extension can view/edit csv but can only view excel... this is way too asymmetric for me
    - Viewing Excel files might be good for simple tables but I doubt that there is a "good" preview for more complex scenarios

- time and effort is also a big thing here ;)
- merging would also mean that we would need to use one js table component
  - Excel viewer is powerd by Wijmo (GrapeCity) and I think they want to show what their component(s) can do. So they probably would want to stick with it


I think most users of this extension only want the csv features, why bloat the extension with all the Excel features?

Is there a reason why you need a single extension?

**Comment by mesajidiqbal** [comment]
I tried "Data Preview" and "Data Set Preview" but I didn't find it as user friendly as "Edit CSV" and as pretty to eye as "Excel viewer".
So, I thought of something like this:
    - Assume the new extension name is "Data Viewer" (An imaginary name which I thought)
    - The extension supports the flat-files (csv, tsv etc) and excel
    - Below is my thinking for the extension features and functionalities

-  For flat-files (csv, tsv, txt etc)

1. When you click on a csv file it opens up like shown in the image "csv_data_view.png" (With values in different colors) ("rainbow csv" has already this feature)
    - Some options available in command palette (as in image) (Some options are already in rainbow csv (not all) and some extra options (e.g markdown table etc)) (Some extra features of "rainbow csv" (sql like joins etc) can be removed)
    - An icon to view it in tabular form (Top right, near code-runner)
![csv_data_view](https://user-images.githubusercontent.com/44871521/86040067-ffd50a00-ba60-11ea-8ff3-ba16369ed8bc.png)

2. After clicking the table icon a tab similar to the image "csv_tabular_view.png" opens up with following functionalities:
    - Options to toggle header, total/last row, first/index col, last col (As can be seen in top-left bar)
    - Option to change delimiter and reload file (top-right)
    - Option to edit the file (top-right, after delimiter option)
    - Option to filter data (See the filter icons after column name)
![csv_tabular_view](https://user-images.githubusercontent.com/44871521/86040100-0f545300-ba61-11ea-8c70-26fdda42d991.png)

3. After clicking the edit file option a page similar to the image "csv_edit_view.png" opens up with below functionalities:
    - Options to add rows/columns
    - Option to delete column (As "edit csv" already gives a delete icon after column name)
    - Option to trim all the data values
    - Options to apply/save the changes
![csv_edit_view](https://user-images.githubusercontent.com/44871521/86040119-1713f780-ba61-11ea-8a9c-4d138896de3e.png)

- For excel files (xls, xlsx)

1. When you click on an excel file it directly opens up the file in tabular form as in image "excel_tabular_view.png" with following functionalities:
    - Options to toggle header, total/last row, first/index col, last col (As can be seen in top-left bar) - similar to csv option
    - Option to filter data (See the filter icons after column name) - similar to csv option
    - Option to export the one/all sheet as csv (top-right)
    - Tab in bottom bar for all sheets and navigation icons ("Excel viewer" already has this feature)
![excel_tabular_view](https://user-images.githubusercontent.com/44871521/86040131-1ed39c00-ba61-11ea-99a8-a671b436f2a2.png)

Note: Only sheets with text data should be supported to keep the extension light-weight (Sheets with image/graphs should not open)

**Comment by ZurMaD** [comment]
Would be interesting. But the question: is necessary or in which ways improve the job?

**Comment by RandomFractals** [comment]
hah! this is like all over the place now? oy!

https://github.com/mechatroner/vscode_rainbow_csv/issues/65#issuecomment-689599858

**Comment by janisdd** [comment]
I think this can be closed now because all extension authors agreed on that.
