### ISSUE TITLE
Add possibility to freeze first column

### ISSUE THREAD

**Issue by Elmegaard** [janisdd/vscode-edit-csv#33]
For some projects it's good to know the first column for files where the first column is an identifier for the row and it has a lot of columns. Some of the files I am editing has 50+ columns so you will either have to select the row or remember the position to edit columns far to the right in the editor. This can become a bit of an issue if you are scrolling while looking at columns for different rows.

Amazing extension though, thanks.

The feature with showing the header is also very nice, could be the same for this to be honest. We are using strings to identify the id of the column instead of the index. Could be the same here as you did with the header, replace the column index with the first column. Both features would be amazing though.

**Comment by janisdd** [comment]
I'm not sure if I understood this correctly...
The first column has an id that identifies the row (in addition to the row index)?
e.g.

|   | id  | col2 | col3 | ... | col50 |
|---|-----|------|------|-----|---|
| 0 | abb | ...  | ...  | ... | ... |
| 1 | bbb | ...  | ...  | ... | ... |
| 2 | bcb | ...  | ...  | ... | ... |

And when you scroll to the right to see col50 you not longer see the `id` column and this is the issue?
If yes, are you editing such files often (should be a config option) or only occasionally (should be a setting in the extension ui)?

**Comment by Elmegaard** [comment]
Exactly. I am doing this very often, it would be quite nice with a config option for it.

**Comment by janisdd** [comment]
I've added a new config option `initiallyFixedColumnsLeft` and (renamed `fixFirstXRows` to `initiallyFixedRowsTop`).
The ui now also offers changing this for the current table.

**Comment by Elmegaard** [comment]
Amazing thanks!

**Comment by eugene-kim** [comment]
Thank you @janisdd for the freeze column setting!
