### ISSUE TITLE
Auto reload from disk

### ISSUE THREAD

**Issue by Elmegaard** [janisdd/vscode-edit-csv#37]
Would it be possible to make the csv editor automatically detect changes to the file on disk, and reload? For example, if I do a git pull. We had an unfortunate accident yesterday with a few commits getting overwritten, because we didn't think of reloading the editor before making our changes. It could just be the "simple" notepad++ version, where you get a notification if there are changes on the disk, so you know at least. But it would be even better for us if it just did it automatically.

EDIT:
I looked a little bit at your code, but I am by no means and expert in either typescript or vs code plugins. I think you could just add a "file has changes" check to preReloadFileFromDisk I would assume, and only continue if there are actually changes to the file on disk. Then call that function every x seconds, would be a very simple solution. It would then work exactly like Notepad++, except you would need something to handle if people press "no" to the popup, so it doesn't just keep asking, but disable the infinite reload check until the next save or reload from disk.

EDIT 2:
If you could then on top of this add 2 settings, one for enabling this feature and another for whether it should ask before reloading. You can of course default them however you want. That would be amazing.

**Comment by janisdd** [comment]
I thought I could get away without automatic file reload but probably not ;)

This would be a nice feature but I currently have no idea how to implement this in a clean way...
Checking the file every X seconds would work but I think the default approach (how vs code and other tools do it) is with file watchers.
From my understanding the OS then watches the file for you and you get an event fired when the file changed.
The only thing I'm not sure yet is how the extension own writes (through vs code) and the file watcher would play together.
When you click save in the extension you want to ignore the next file watcher change event...

For the setting I would always ask to reload before overwriting the table if the table has any changes

I'll take a look at this

**Comment by Elmegaard** [comment]
Thanks! It would be an amazing feature and we could finally start getting some of the less tech-savy guys on our project moved to using this instead of the random old editors they are using.

And yes, it makes sense to always ask if there are changes, but if there is not, it should just overwrite. Another problem we may face then is, it always shows changes on first opening the editor (at least for us), even if there are no changes. So if I click "edit csv" on a .txt file, it opens your window and it immediately have changes. It is a minor problem though.

**Comment by janisdd** [comment]
>Another problem we may face then is, it always shows changes on first opening the editor (at least for us), even if there are no changes.

If you could provide such a file (removing sensitive data) a could have a look. My best guess is that not all rows have the same number of cells (some were expanded). When I change a `.csv` into `.txt` it works as expected (I need to trigger the command via the command pallet).

Also if you plan on editing (changing) the csv files, please read the `Important Notes` in the readme (e.g. empty lines are skipped)

**Comment by Elmegaard** [comment]
Ahh that could be it then, we add an empty line on the end of the file.

**Comment by janisdd** [comment]
I think it is working on a basic level with `vscode.workspace.createFileSystemWatcher` but this only works for files inside the current workspace...
If you just drag and drop a file from another folder (not the workspace folder) vs code gives no notifications.

There is also an issue in vs code that `vscode.workspace.createFileSystemWatcher` can watch any file/folder https://github.com/microsoft/vscode/issues/3025

I'll also check https://github.com/paulmillr/chokidar which seems to do the same (but is obviously not built-in).

I also wonder if a setting to disable file watching is necessary as this should be always enabled (can't think of a reason not to)? 

@Elmegaard I tested `.txt` and `.csv` files with empty lines at the end (only new line characters) and I don't get the changes indicator... However on save/apply the new lines are gone (as expected)

**Comment by Elmegaard** [comment]
That is just perfect! We are doing everything in work spaces anyway, which is why I want settings for everything, so I can set it up for the other guys.

The way I added the new line is this setting: "files.insertFinalNewline": true
It could be something else though, I am not sure.
These are all my settings:
```"settings": {
    "files.associations": {
      "*.txt": "tsv"
    },
    "csv-edit.readOption_hasHeader": "true",
    "editor.formatOnSave": false,
    "csv-edit.initiallyFixedColumnsLeft": 1,
    "csv-edit.readOption_quoteChar": "",
    "csv-edit.writeOption_quoteChar": "",
    "csv-edit.readOption_escapeChar": "",
    "csv-edit.writeOption_escapeChar": "",
    "csv-edit.retainQuoteInformation": false,
    "csv-edit.readOption_comment": "",
    "csv-edit.writeOption_comment": "",
    "files.insertFinalNewline": true
  },```

**Comment by janisdd** [comment]
I nee to do some more testing before this can be released.
For non-workspace files there is now a warning when the file on disk gets changed with instructions how to manually reload it.

Even with the provided settings it's working fine for me... no change indicator

**Comment by Elmegaard** [comment]
Weird, I will look into it myself then, not that it is a huge issue for us.

**Comment by janisdd** [comment]
Finally I got time to publish this. It should work as expected for workspace files, for non-workspace files there is only a warning displayed to manually refresh (with instructions).

**Comment by Elmegaard** [comment]
Thank you very much!
