### ISSUE TITLE
To install the extension locally via git clone

### ISSUE THREAD

**Issue by gusbemacbe** [janisdd/vscode-edit-csv#38]
Hello!

Building it locally does not help. I would like to install it locally via `git clone` for not breaking the symlinks in other workspaces if I keep updating the extension. Updating the extension will change the folder version, resulting in broken symlinks in other worksapces.

**Comment by janisdd** [comment]
I'm not sure if I understand this correctly. You want to build it locally? What do you mean by "building"? Install the extension or create a .vsix file?

When you install an extension it is installed into e.g. `/Users/USER/.vscode/extensions/` on mac. You want to symlink the folders inside there? Maybe you could give some more context?

**Comment by janisdd** [comment]
This is probably a problem with how vs code handles extension version. Not much I can do about.
