### ISSUE TITLE
Cannot view two files with the same name in different folders

### ISSUE THREAD

**Issue by victor-moreno** [janisdd/vscode-edit-csv#39]
If two csv files in different folders are opened, edit as csv the second one will throw an error:

Could not create an editor instance, error: tried to add a new instance but we got old one (with the source uri)

**Comment by janisdd** [comment]
Works fine for me. Maybe you tried to open the same file twice? 
The instances/editors are separated/stored by sourcefile Uri. As every file has a unique Uri (like a path) this should work.

**Comment by janisdd** [comment]
I can't reproduce this and you probably opened the same file twice somehow.

*closed due to inactivity, missing info*
