### ISSUE TITLE
" " Gets changed to another value

### ISSUE THREAD

**Issue by JSPieterse** [janisdd/vscode-edit-csv#4]
If you have a empty cell and you want to change its value to " "
The value is displayed as " " but saved as """ """

So in the csv file it should look like this: value1," ",value2
When you apply and save it get changed to: value1,""" """,value2

Awesome app though.

**Comment by janisdd** [comment]
Thanks for the hint. The default for handsontable (table ui) is to trim cell values immediately after editing. I'll make a new option to set the trim behavior.

I wonder which case (trim or not) is better as default...
When you edit you won't expect that your text get changed after the edit. On the other hand when you accidentally added an additional whitespace it would be nice if that is trimmed automatically.

I'm tending towards not trim as default.

Any thoughts?

**Comment by JSPieterse** [comment]
I would agree to not trim by default.
Maybe an option button to check for and remove whitespace.
Its hard to choose since you never know what the user's intention was.

**Comment by janisdd** [comment]
You're right, a button is probably better...  
I added a new button to remove whitespace in all cells

**Comment by JSPieterse** [comment]
Thanks



Kind regards
Joe

On 3/07/2019, at 10:01 AM, janisdd <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #4<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjanisdd%2Fvscode-edit-csv%2Fissues%2F4&data=02%7C01%7C%7Cfd41830551204a9648fc08d6ff38c60a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636977016645964877&sdata=pKV0J6SI4OAC5iv1CUb3UcW3nTxvZofJRr9hkCq1F5I%3D&reserved=0>.
