### ISSUE TITLE
Config extensions that are recognized

### ISSUE THREAD

**Issue by victor-moreno** [janisdd/vscode-edit-csv#40]
Enhancement request:
Config extensions that are recognized. 
I would like to add: .txt / .dat / .out

Thanks

**Comment by janisdd** [comment]
As mentioned in https://github.com/janisdd/vscode-edit-csv/issues/28 the file extensions need to be hard coded into the package.json. This would be a bad user experience for all users that use .txt / .dat ... files that not contain csv data.

However you can use the command palette to execute `CSV: edit as csv` or you can assign a shortcut in vs code to execute the `CSV: edit as csv` command.

**Comment by janisdd** [comment]
As long as the extensions cannot be dynamically configured this won't be implemented (downgrades other users experience, see comment above).

**Comment by janisdd** [comment]
I looked through the docs and I thought https://code.visualstudio.com/updates/v1_49#_in-operator-for-when-clauses would give use the needed functionality but I couldn't get it to work...
However, I also found https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file where you can map `*.txt -> csv` and all your needed extensions
