### ISSUE TITLE
Edit as csv option disappeared

### ISSUE THREAD

**Issue by CTCDGL** [janisdd/vscode-edit-csv#41]
Hello!

Since yesterday on vs-code insiders the option to "edit as csv" has disappeared from my user interface for certain csv files.

To create a simple example to show you, I made a new .csv file and noticed that with the new file, the option still shows up. See screenshot:
![works](https://user-images.githubusercontent.com/70373117/91549391-29a69200-e927-11ea-92f1-579b88e30994.png)

However, for my older .csv files, the option disappears. See screenshot:
![gone](https://user-images.githubusercontent.com/70373117/91549441-3c20cb80-e927-11ea-9e4c-1d0fcc723042.png)

However, since I've created a keyboard shortcut to launch "edit as csv", I am still able to edit these files by using the keyboard shortcut. See the screenshot:
![shortcut works](https://user-images.githubusercontent.com/70373117/91549504-5490e600-e927-11ea-9a9e-87657ab31316.png)

However, I do not want to rely on the keyboard shortcut. I would rather have the option to click the button as it used to appear for all my .csv files and as it still shows up in the first picture I show above.

Furthermore, I noticed that when I first create a .csv in VS-code Insiders, the "Rainbow CSV" seems to take no effect (see the first screenshot above). However, when I close and re-open the file, the color-coding shows up... But now "Edit as csv" has gone away! See screenshot:
![gone too](https://user-images.githubusercontent.com/70373117/91550179-6c1c9e80-e928-11ea-8eb8-de9a5dd67252.png)

It seems that there is a conflict between these two extensions, although i never noticed such a conflict before yesterday.

Any ideas how I need to fix this?

**Comment by janisdd** [comment]
In the past there were some issues with vs code insider builds... The way they were resolved is by waiting for the next official vs code release ;)
I think the best option is to wait for the next vs code update. If the issue still persists some days before the official update I can look into this.

**Comment by janisdd** [comment]
It could also be related to https://github.com/janisdd/vscode-edit-csv/issues/28
You can check the recognized file type at the bottom right. It should save `CSV`... sometimes rainbow csv likes to swap this for e.g. `CSV (semicolon)` or other types. If you click on the text you can change the file type (how the file is treated).

**Comment by janisdd** [comment]
I think this can be closed now. You can try to disable the rainbow csv extension and to reproduce this. If it's still there feel free to reopen the issue.
