### ISSUE TITLE
Allow Multiple Column sorting

### ISSUE THREAD

**Issue by violentmagician** [janisdd/vscode-edit-csv#42]
Handontable allows for Multi-column sorting. Would it be possible to add the ability to do multiple column sorting?

Please see the [Multi-column sorting Tutorial](https://handsontable.com/docs/6.2.2/demo-multicolumn-sorting.html) from the docs.

**Comment by janisdd** [comment]
Yeah, should be doable. But there are a few things to keep in mind/checklist:

- no ui buttons, only with `click + ctrl/cmd`
- must work with light/dark themes
- hint in the help modal describing `ctrl/cmd` usage

Currently I have other work to do, so this could take some time.

**Comment by janisdd** [comment]
After looking at the documentation again I saw that Multi-column sorting is a pro feature...
So this must be re-implemented which takes much more time.
Don't expect this in the near future.

**Comment by janisdd** [comment]
Will ship with the next release. Also keep in mind that all data is treated as text (so sorting for numbers will probably be "wrong")
