### ISSUE TITLE
White background when editing as csv

### ISSUE THREAD

**Issue by CTCDGL** [janisdd/vscode-edit-csv#43]
I installed the latest version of VS Code Insiders, and now when I "edit as csv" I get a really ugly white background. Since much of the UI uses gray text, it is also low-contrast and hard to read now.

![image](https://user-images.githubusercontent.com/70373117/92241586-be2c6980-eebe-11ea-8cd6-78f934cc3eae.png)

Tips?

**Comment by janisdd** [comment]
I see you like to use the insider builds... I'm sorry but they are beta builds and I won't invest time in fixing issues that are likely not on my end.

**Comment by CTCDGL** [comment]
Yes, I use VS Code Insiders so that I can synchronize settings across different machines since this is not available without using Insiders (as far as I know).

Thanks anyway!
