### ISSUE TITLE
Background Problem

### ISSUE THREAD

**Issue by tbidwell** [janisdd/vscode-edit-csv#44]
With the August 2020 VScode update, the "edit as csv" view's background is now suddenly white. I backed my VScode version up to July 2020 and it turned it back to the default grey of the Default Dark+ theme.

![image](https://user-images.githubusercontent.com/7853090/92966986-7c636c00-f446-11ea-930f-90a3943030bf.png)

The arrows point to what turned white. The text color stayed the same when the background was white in those places, which also made it difficult to read non-button/dropdown text.

**Comment by janisdd** [comment]
Uh! This is a serious issue, I'll look into it as fast as possible. Thx for letting me know.

**Comment by janisdd** [comment]
Should be working now.

**Comment by tbidwell** [comment]
Whoot! It's behaving now.

You are fantastic! (And fast!)

I've come to rely quite a bit on this...Excel/Google are nice and all, but for my job, working with the raw side has made my life a _lot_ easier. :)
