### ISSUE TITLE
After edit and reopen, extension takes a long time to render table

### ISSUE THREAD

**Issue by ngc2392** [janisdd/vscode-edit-csv#45]
I have a CSV file with about 8,500 rows. I can open the file no problem. If I make a modification (deleting a column, modify a cell), save the changes, close the extension window, and then open the file again (either through the command pallet or clicking 'Edit as csv'), it takes a long time for the extension to load the CSV. 

Next to the 'Apply changes to file' it says 'Rendering table...'. When I deleted a column, saved, and reopened the file, it was 'Rendering table...' for close to an hour. 

I did a similar process with a CSV file with about 5000 rows, and it opened right away after I saved the file.

I can provide any other information if needed.

**Comment by janisdd** [comment]
Strange, I always test with a file 14 Columns & 100 000 Rows and I takes normally ~10s to load/render the table (MacBook 15" Pro 2016). Normally all methods of opening the extension/table are equal in speed.
Did you close the extension window fully and reopen it? Or do you click on "Edit csv" while it is still open?
Or does your file has like 1000 Columns ;)?

Maybe you give a step by step guide to reproduce this?

**Comment by janisdd** [comment]
Gonna close this until we have more information. Feel free to reopen.
