### ISSUE TITLE
Add extension setting: file extension

### ISSUE THREAD

**Issue by aganm** [janisdd/vscode-edit-csv#47]
### Version
- vs code plugin

### Feature
I have csv files that do not have a .csv extension. It would be handy to have a configuration setting to add different file extensions.

**Comment by janisdd** [comment]
As far as I know this is not possible for extensions. This is probably a duplicate of https://github.com/janisdd/vscode-edit-csv/issues/40

However, you can configure this in vs code itself: https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language

Basically in the settings search for `files.associations` and add an entry for `*.yourExtension` to `csv` and it should work (you might need to reopen the file).

**Comment by aganm** [comment]
Thanks!
