### ISSUE TITLE
View resetting and column resizing on save button press

### ISSUE THREAD

**Issue by BarnabasMakkay** [janisdd/vscode-edit-csv#48]
### What OS?
- Windows 10 Pro (version 1909)

### Version?
- vs code plugin

### Description
When pressing the one of the save buttons the view is reset (jumps to top left) and the custom set column size is reset to the default length (that matches text length)

Why is this an issue? I'm currently editing a large csv file that contains localization text for multiple languages. 
- Resetting position takes me away from where I was making edits
- Resetting column size is annoying as some text is very long (e.g. smaller paragraph), so it's easier to set custom width

### Steps to reproduce
A step by step guide how to reproduce this issue/bug.
1. Create a csv file containing a few rows (enought to enable vertical scrolling) and a few columns (some of which contains cells with very long text that enables horizontal scrolling). 
2. Scroll to the bottom of the file and shrink the long columns so that you can view all columns without scrolling. 
3. Make some modifications to any of the cells and press either the "Apply changes to file and save" or the "Apply changes to file". 
4. As a result, the editors position should be reset to the top left of the "spreadsheet view" and the long columns should be expanded to their "default" size. 

Expected behavior:
- View stays where it was at the time of pressing the button
- Custom set column widths are not modified
- These values/parameters are temporarily stored so when reloading the view they can be loaded

**Comment by BarnabasMakkay** [comment]
Yes I do have csv-edit.enableWrapping set to true. I'm using latest release build, not insider.

**Comment by janisdd** [comment]
Can you try to reproduce it with this file? And if so the steps you did.
[test3.txt](https://github.com/janisdd/vscode-edit-csv/files/5374467/test3.txt)

I checked with Windows 10 1903 (Education) and it worked normally.

**Comment by janisdd** [comment]
Ah and please also do a test with `csv-edit.shouldWatchCsvSourceFile` turned off

**Comment by janisdd** [comment]
@BarnabasMakkay Can you please check with the `test3.txt` file I provided (you need to rename it to csv as github disallows csv)? Any maybe check with another pc?

**Comment by janisdd** [comment]
Might be fixed by https://github.com/janisdd/vscode-edit-csv/commit/a2012fa1ab82f2ca2bd7f694658cefbe4892b62f

it should
- keep column sizes when resetting data and
- keep column sizes on auto reload file content from disk

Needs a bit more testing but will ship with the next release
