### ISSUE TITLE
Header is not display in the header line

### ISSUE THREAD

**Issue by mkloar** [janisdd/vscode-edit-csv#50]
### What OS?
- Windows

### Version?
- vs code plugin

### Description
When the .csv file has the only header and no data rows, then the header is not displayed in the header row. When adding data row, the header is displayed properly.

**Example:**
![csv-with-only-header](https://user-images.githubusercontent.com/17946736/99062618-8cf9a500-25a3-11eb-8bdb-02577c32f9a1.png)

**CSV file content:**
`SomeHeader;SomeHeader`

**Edit csv settings:**
Csv-edit: Read Option_has Header: true
Csv-edit: Read Option_has Header: true
Csv-preview: Has Headers: true

### Steps to reproduce
1. Create CSV file with the only header
2. Open CSV file in the extension
3. Header is not visible in the "header line" but instead is displayed as data

**Comment by janisdd** [comment]
The current behavior is by design. Handsontable must display at least one row (from what I've found).
With this limitation I'm not sure what should be done differently here.

Any suggestions?

**Comment by mkloar** [comment]
> The current behavior is by design. Handsontable must display at least one row (from what I've found).
> With this limitation I'm not sure what should be done differently here.
> 
> Any suggestions?

I would say that if there's one row and settings for the header is enabled then this row is displayed as a header column.

**Comment by janisdd** [comment]
So in your example it should be 
_ | SomeHeader | SomeHeader
---|---|---
1| SomeHeader | SomeHeader

I've expressed it badly... there must be row 1 + the header row in handsontable. You can't just have the header and no rows.

**Comment by mkloar** [comment]
> So in your example it should be
> 
> _	SomeHeader	SomeHeader
> 1	SomeHeader	SomeHeader
> I've expressed it badly... there must be row 1 + the header row in handsontable. You can't just have the header and no rows.

Aha, yeah I want that behaviour, but as you said this is not possible. 

Is it possible that if you have enabled an option for the header then if you add another row, then it will automatically change first row into header and last row will become row number 1.

**Example before adding new row:**
| - |Column 1|Column 2|
|:-----------------|:-----------------|:------|
|1|	SomeHeader|SomeHeader|
 
**After adding additional row**:
| - |Column 1|Column 2|
|:-----------------|:-----------------|:------|
|1|	SomeHeader|SomeHeader|
|2| SomeRow Data  | Some row data 2|

**Immediately after completing the row change to this:**
| - |SomeHeader|SomeHeader|
|:-----------------|:-----------------|:------|
|1| SomeRow Data  | Some row data 2|

If this is an option I can contribute...

**Comment by janisdd** [comment]
I think this could be a bit misleading for some users as there would nothing happen if they toggle the "has header" option when they have only 1 row.
On the other hand it's should be really rare that you only have 1 row and want to display a header...

Maybe we should just go with your suggestion and see if someone complains.

By "contribute" do you mean the idea or code?

**Comment by mkloar** [comment]
Maybe...Both :+1:

**Comment by janisdd** [comment]
Cool, I'll set this to "in progress".

If you want, you can try this.
This weekend I have not much time but I can have a look next weekend (probably).

**Comment by janisdd** [comment]
I think this should be fine now but I have to do some more testing...

If you want you can clone this and try it locally.

**Comment by mkloar** [comment]
This is perfect :) Do you have any plans when will this be released?

**Comment by janisdd** [comment]
I think next weekend... I want to fix #51 and put it in the update too

**Comment by mkloar** [comment]
Perfect :) I can close this issue now. THANKS!
