### ISSUE TITLE
Escape Characters are not evaluated

### ISSUE THREAD

**Issue by Heinerion** [janisdd/vscode-edit-csv#52]
### What OS?
- Web-Version
- Windows 10 / VS-Code:
> Version: 1.51 .1 (user setup)
> Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
> Date: 2020-11-10T23:34:32.027Z
> Electron: 9.3.3
> Chrome: 83.0.4103.122
> Node.js: 12.14.1
> V8: 8.3.110.13-electron.0
> OS: Windows _NT x64 10.0.17763

### Version?
- vs code plugin 0.5.2
- browser (https://edit-csv.net/) v1.1.1

### Description
I set up escape characters (first try (a): `\` second (b): `=`).
My expectation ist, that `a,b\,c=,d` will render 
(a) `a | b,c= | d`
(b) `a | b\ | c,d`

### Steps to reproduce
1. load following csv
```csv
Name,field-with-escape,field-without-escape
foo,1=,2345,0
bar,98\,765,1
baz,456\,0,2
```
2. Set `EscapeChar` to `\`
a. **expected**  `foo|1=|2345|0`, next line: `bar|98,765|1`
b. **got** `foo|1=|2345|0`, next line: `bar|98\|765|1`
3. Set `EscapeChar` to `=`
a. **expected**  `foo|1,2345|0`, next line: `bar|98\|765|1`
b. **got** `foo|1=|2345|0`, next line: `bar|98\|765|1`

**Comment by janisdd** [comment]
My "render" do you mean writing out the csv oder rendered in the table?

The `EscapeChar` option is used to escape the `QuoteChar` in the cell value... (we use the option `escapeChar` from papaparse: https://www.papaparse.com/docs)

I see this is not obvious from the ui, I should add a `?` hint with tooltip.

If you want to escape the `,`, you need to quote the field/cell:

```csv
Name,field-with-escape,field-without-escape
foo,1=,2345,0
bar,"98,765",1
baz,"456,0",2
```
(I think this is what you want?)

**Comment by Heinerion** [comment]
Yes, in deed that is what I am looking for, tank you!

**Comment by janisdd** [comment]
I've added the hint but as this is a very minor change I won't release an update yet.
This will ship with the next update (e.g. next fixed issue).

We can leave this open as a reminder :)
