### ISSUE TITLE
Feature request: Add keyboard shortcut to add row below/above

### ISSUE THREAD

**Issue by caugner** [janisdd/vscode-edit-csv#53]
### Version?
- **both**

### Feature

As far as I can tell, rows can only be added using the "Add row" column or via the Row Context Menu. However, it would be extremely helpful if this would be possible using keyboard shortcuts:

* <kbd>Ctrl</kbd> + <kbd>Insert</kbd> = Insert row below (and focus first cell of that row)
* <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Insert</kbd> = Insert row above

**Comment by janisdd** [comment]
Just to be sure, you mean inserting above/below the current selected cell (its row)?
And with <kbd>Insert</kbd> you mean <kbd>Enter</kbd> or what key is that?

The other thing I'm concerned about by introducing shortcuts is that they cannot be configured and might collide with vs code shortcuts

**Comment by caugner** [comment]
> Just to be sure, you mean inserting above/below the current selected cell (its row)?

Exactly.

> And with Insert you mean Enter or what key is that?

With <kbd>Insert</kbd> I mean the following key:
![grafik](https://user-images.githubusercontent.com/495429/102250338-be97c000-3f03-11eb-9807-f3eb4bca0c4d.png)

<kbd>Return</kbd> ("Enter") is already used to navigate cells up/down and <kbd>Ctrl</kbd> + <kbd>Return</kbd> creates a line-break, so those keys are already used (even though <kbd>Return</kbd> in the last row could implicitly insert a row below and focus that new row in the same column).

**Comment by janisdd** [comment]
I would rather not exclude laptop and mac users from this feature so there might be a better shortcut...
It's somewhat related to the search dialog which has currently ctrl+f/cmd+f

I think this feature would be nice but I also have to do some investigation which key could be used for this (and not interfere with the handsontable shortcuts/editing).

>(even though <kbd>Return</kbd> in the last row could implicitly insert a row below and focus that new row in the same column).

There is already a setting for this: `csv-edit.lastRowEnterBehavior`

**Comment by janisdd** [comment]
After some testing a came to the conclusion the shortcut is good even if it cannot be used by mac and laptop users.
To resolve this I've added small buttons next to the add row/col buttons to insert rows/cols. The new buttons only take ~40 more px, should be ok.

Notice there is an issue with sorting and/or reordering of rows/columns in combination with inserting rows/cols... I've created an issue for this #54 

However, this will ship in the next couple of days :)

**Comment by dannyconnell** [comment]
Hi @janisdd . I've just started using Edit csv and I'm really blown away by it. I downloaded several standalone CSV editing apps and none of them came close. So thank you so much, your work is really impressive! However, for me it would go from almost perfect to perfect if I could use these keyboard shortcuts on my Mac. I know we have the buttons, but like a lot of developers, I like to stay on the keyboard as much as possible. Is there any chance you could add some alternative keyboard shorcuts for Mac? Or, even better, make these keyboard shortcuts configurable within VSCode? Thanks!

**Comment by janisdd** [comment]
Yeah that’s the problem with key bindings in extensions… last time I looked into it I couldn’t find how extensions can make a liste of shortcuts and make them configurable. I know that the extension commands can have key bindings but I doubt that they work when the focus is inside a webview/extension. I’ll look into that again.

**Comment by dannyconnell** [comment]
Thanks @janisdd that's hugely appreciated!

**Comment by janisdd** [comment]
After some investigating it seems that there is no good way to achieve this… There are some open issues in vscode itself (82592, 85879). Defining commands in the extension (which can be configured in the vscode keyboard shortcuts ui) are not recognized in the webview (while the editor is open). Some special (?) shortcuts seems to work always e.g. `cmd+p`...
However, I won't create some custom string to key mapping just for this extension. 

That being said, we could hardcode a shortcut for adding row up/down for mac users.
**What shortcut would you prefer?**

*But note that this is only a temporarily solution until vscode has a way to handle this „officially“ (but the shortcut will probably stay the same … so maybe not that temporarily ;)*

**Comment by dannyconnell** [comment]
Thanks for looking into this @janisdd 

Maybe:

<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Up</kbd> : Add row above
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Down</kbd> : Add row below
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Left</kbd> : Add column left
<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Right</kbd> : Add column right

Or if you wanted to reduce the risk of clashes:

<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>Up</kbd> : Add row above
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>Down</kbd> : Add row below
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>Left</kbd> : Add column left
<kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>Right</kbd> : Add column right

**Comment by janisdd** [comment]
I think I got it working now... It' actually quite cumbersome doing it with handsontable because the arrow keys events (and combinations) are processed first in handsontable and then bubbles up. The current solution won't work when the shortcuts are configurable but luckily we aren't there yet.

I think we should go with the shift shortcuts to avoid clashes.

After playing around I find the behavior of selecting the first cell in the new row a bit annoying. Maybe this is only bad for testing and in real world scenarios selecting the first cell is actually more desired?
@dannyconnell Do you think the current col should stay the same? Or is selecting the first cell in the new row better? Maybe a new extension option for this?

**Comment by dannyconnell** [comment]
@janisdd great to hear you're making progress! Personally I would leave the originally selected cell selected - whether adding a row OR a column. This way, if you wanted to, for example, add one row above the current cell and one row below, you can do this just by firing the keyboard shortcuts in quick succession - without having to then move cell. But it's not a deal breaker whether it does this or selects the first cell in the new row / column. Yeah, an option would be great!

**Comment by janisdd** [comment]
There will be two new options: 
- `insertRowBehavior`
  - `focusFirstCellNewRow`: focus the first cell in the new row (default)
  - `keepRowKeepColumn`: keep the currently selected cell
- `insertColBehavior`
  - `keepRowFocusNewColumn`: we stay in the same row but the cell in the new column is selected
  - `keepRowKeepColumn`: keep the currently selected cell (default)

Hm, I also like the approach to keep the selected cell, feels more intuitive to me.
Maybe we should change the default to `keepRowKeepColumn` for both (which is actually the default for handsontable out of the box).

Let's give issue creator some time... @caugner are you ok with changing the default to not focus the first cell in the new row (when inserting a row)? You can go back the current default behavior when setting `insertRowBehavior` to `focusFirstCellNewRow`.

**Comment by janisdd** [comment]
OK, I think this was enough time… we will go with the new defaults.

This will be in the new update but before this I want to fix the issue #58 (and only release one update)

**Comment by dannyconnell** [comment]
That's great news @janisdd I'll look forward to it. Thanks for all your work on this. 👍

**Comment by janisdd** [comment]
Update is love now...
However, there is issue #54 so watch out after sorting or anything that changes the row/col order, inserting new rows/col will not work properly (add row/col strangely works)

I consider to add a warning if some reordering is detected and one tries to insert rows/col (as I will probably forget about the issue myself ;)

**Comment by dannyconnell** [comment]
Thanks very much @janisdd . Tried it out and it's working great!
