### ISSUE TITLE
Add support for "csv (semicolon)" language id

### ISSUE THREAD

**Issue by mechatroner** [janisdd/vscode-edit-csv#55]
Hello,
Please add support for `csv (semicolon)` language id to improve interoperability with Rainbow CSV plugin (see this bug  mechatroner/vscode_rainbow_csv#82 ), And maybe `csv (pipe)` too. I understand that this bug is probably my fault since at some point I switched language id from `CSV (semicolon)` to `csv (semicolon)` to better conform to VSCode recommendation to use lowercase language ids. 

As a side note, I think that it is very unfortunate that the situation with csv-related language ids is so chaotic, I think we should work together and try to standardize the filetypes and language ids for semicolon-separated files and pipe separated files since these are the most used dialects after csv and tsv. I also don't like the arbitrary names that I choose for them, `csv (semicolon)` and `csv (pipe)`, so I hope ultimately we can come up with something better. 
There are some attempts to standardize csv dialects, e.g. https://www.w3.org/TR/tabular-data-model/ but this model doesn't address file extensions and file types, unfortunately, so maybe someone can come up with a proposal to include this terminology into the metadata model.

**Comment by janisdd** [comment]
Ok, I've added these language ids (all from the readme):

- csv (semicolon)
- csv (pipe)
- csv (whitespace)
- csv (tilde)
- csv (caret)
- csv (colon)
- csv (double quote)
- csv (equals)
- csv (dot)
- csv (hyphen)

**Comment by mechatroner** [comment]
Thank you!
