### ISSUE TITLE
Do not insert "" in empty columns

### ISSUE THREAD

**Issue by mlatysh1** [janisdd/vscode-edit-csv#56]
### Version
- vs code plugin
### Feature

After writing a table to file, empty cells are saved as `...,"",...`  and I haven't found an option not to quote empty values.

**Comment by janisdd** [comment]
For the docs: Empty strings and null values are treated the same way, both get written without `""`

What might causes the `""` to appear is the option `csv-edit.retainQuoteInformation`.
So I guess your column headers are quoted?

Try disable this option and see if it works.

**Comment by janisdd** [comment]
Also for the docs: handsontable insert new rows (via `hot.alter` with null values (as cell values) but there is maybe an option to change this: https://handsontable.com/docs/6.2.2/Options.html#dataSchema

**Comment by mlatysh1** [comment]
> For the docs: Empty strings and null values are treated the same way, both get written without `""`
> 
> What might causes the `""` to appear is the option `csv-edit.retainQuoteInformation`.
> So I guess your column headers are quoted?
> 
> Try disable this option and see if it works.

Oh, thank you! changing `csv-edit.retainQuoteInformation` to `false` worked for me. But btw my headers was not quoted, but I had some quoted cells values. 

For e.x csv like this:
<img width="191" alt="Снимок экрана 2021-02-23 в 21 03 50" src="https://user-images.githubusercontent.com/76155526/108886934-a25a8280-761a-11eb-8e33-a7b2397c2c0a.png">
If i modify it via extension and make it look like this:
<img width="695" alt="Снимок экрана 2021-02-23 в 21 04 18" src="https://user-images.githubusercontent.com/76155526/108886996-b30af880-761a-11eb-8ce2-5504634b494c.png">
apply&save:
<img width="172" alt="Снимок экрана 2021-02-23 в 21 05 11" src="https://user-images.githubusercontent.com/76155526/108887083-d2a22100-761a-11eb-84f8-a59cc920b46f.png">

So that depends on `csv-edit.retainQuoteInformation` ?

**Comment by janisdd** [comment]
Ahh yes, that is definitely not intended...

To make things clear:
- `csv-edit.retainQuoteInformation` should only respect the first row (not empty, not a comment)
- `csv-edit.retainQuoteInformation` should insert quotes for all cells of a column

Well, you found a bug in papaparse :)
I'll fix that and commit a PR to papaparse.

**Comment by janisdd** [comment]
Update is live, please check if it is fixed now

**Comment by mlatysh1** [comment]
Seems that everything is fine now, thanks!

**Comment by janisdd** [comment]
Just had a discussion with the maintainers of papaparse and they told me null and undefined values should never be quoted.

I'm not sure if we should quote empty fields even if `retainQuoteInformation` tells us to quote it? Maybe we need another option on how to treat empty fields regardless of `retainQuoteInformation`?

@mlatysh1 Suggestions?

**Comment by mlatysh1** [comment]
@janisdd On wiki i found an [example](https://en.wikipedia.org/wiki/Comma-separated_values) which actually quotes empty value (third row). 
But as I know usually it is not quoted.
<img width="600" alt="Снимок экрана 2021-03-04 в 12 39 01" src="https://user-images.githubusercontent.com/76155526/109943783-9b043a80-7ce6-11eb-9f31-73ca725dc74f.png">

On my opinion it would be great to have one more boolean write option for example like `quoteEmptyOrNullFields`

**Comment by janisdd** [comment]
Yeah, I think this would be great.

In my opinion `quoteEmptyOrNullFields` should take precedence over `retainQuoteInformation` …

If we have only 2 states (true/false) then `quoteEmptyOrNullFields` would always overwrite… this might break „backwards compatibility“ as we need to specify a new default value for this.

Maybe we need 3 states for `precedence`: true/false/none (where none uses the value of `retainQuoteInformation`).

My feeling goes in the 2 states and default to `false` direction. So by default we would not quote null, empty string, undefined and always overwrite `retainQuoteInformation` (just for these 3 values).

@mlatysh1  Do you agree?

**Comment by mlatysh1** [comment]
@janisdd Yes, sounds good

**Comment by janisdd** [comment]
The option `quoteEmptyOrNullFields` was added. 
I guess this can be closed now.
