### ISSUE TITLE
Feature request: hide comments

### ISSUE THREAD

**Issue by MathiasMagnus** [janisdd/vscode-edit-csv#6]
Hi!

I'm using this extension to display profiling info from CodeXL/rocm-profiler, because this is the only CSV visualizer that works in remote sessions (the others all communicate through sockets/ports which are not enterprise firewall friendly). I am not so much interested in editing the data, just seeing it as nicely tabulated, dark theme friendly spreadsheet. My data usally has 8-9 lines of comments leading the datafile holding metadata of the execution environment. 99% of the times, this is uninteresting, but I cannot turn tell CodeXL to omit these comments.

Could Edit CSV be told to not display comments?

**Comment by janisdd** [comment]
Currently not... but i'll look into that and check if we can add an option for that.
It could take some time because I have some other things to do at the moment.

**Comment by janisdd** [comment]
It took me some effort because hidden rows is only a pro (paid) feature of handsontable and version 7.x.x requires non-commercial use... so I had to build it my own

But I think it finally works now ;)

You can now use the option `initiallyHideComments` to hide the comments (or use the hide comments button)

You will need to install the update and (probably) restart vs code

**Comment by MathiasMagnus** [comment]
Thanks @janisdd, it's a whole lot better now. There is one tiny glitch remaining. Hiding comments doesn't interact with the "Has header" option nicely. If I hide the comments and turn on headers, it uses the first line of the file as header, and not the first non-comment line.

I'm not sure if there's a commonly accepted practice, that the headers are in comments or not. I cannot tell if my tool is doing something unorthodox by storing headers as actual data or not.

This is the data I'm trying to plot currently. (Simple program, just one data line, more complex applications have more data.)

```csv
#ProfileFileVersion=5.6
#ProfilerVersion=5.6.7262
#API=OpenCL
#Application=/home/mnagy/Source/Test-Applications/CL-Include/.vscode/build/CL-Include
#ApplicationArgs=
#WorkingDirectory=
#Device gfx900 Platform Vendor=Advanced Micro Devices, Inc.
#Device gfx900 Platform Name=AMD Accelerated Parallel Processing
#Device gfx900 Platform Version=OpenCL 2.1 AMD-APP (2874.0)
#Device gfx900 CLDriver Version=2874.0 (HSA1.1,LC)
#Device gfx900 CLRuntime Version=OpenCL 2.0 
#Device gfx900 NumberAppAddressBits=64
#Device gfx900 Board Name=Vega 10 XT [Radeon RX Vega 64]
#Device gfx900 PCIE device id=26751
#OS Version=Linux version 4.15.0-50-generic (buildd@lcy01-amd64-013) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 Build 4.15.0
#DisplayName=
#ListSeparator=,
#ForceSinglePass=False
Method, ExecutionOrder, ThreadID, CallIndex, GlobalWorkSize, WorkGroupSize, Time, LocalMemSize, VGPRs, SGPRs, ScratchRegs, Wavefronts, VALUInsts, SALUInsts, VFetchInsts, SFetchInsts, VWriteInsts, FlatVMemInsts, LDSInsts, FlatLDSInsts, GDSInsts, VALUUtilization, VALUBusy, SALUBusy, FetchSize, WriteSize, L1CacheHit, L2CacheHit, MemUnitBusy, MemUnitStalled, WriteUnitStalled, LDSBankConflict
saxpy__k1_gfx9001, 1, 13395, 55, {1048576       1       1}, NULL,         0.17231, 0, 5, 11, 0,     16384.00,        10.00,         3.00,         0.00,         4.00,         0.00,         3.00,         0.00,         0.00,         0.00,       100.00,         2.99,         2.05,      8212.06,      4096.09,         0.00,        33.32,        20.14,        16.75,         5.04,         0.00
```
On simple cases like this, where there's 1 line of useful data and 18 lines of metadata, being able to hide comments is much more useful than displaying headers correctly. (Naturally, having both is the best UX.)

**Comment by janisdd** [comment]
Ah you're right, comments and "Has header" option should work together...

I think using the first non-comment line as header should be ok.

**Comment by janisdd** [comment]
The new update should fix this. However when you have data like you posted the first column size will be pretty wide. This is because the way "hide comments" works (the row width is still used).

You can manually resize the column or if you know the column will never be larger than X px then you can set the option `Double Click Column Handle Forced With` to that value and double-click on the coulmn resize handle to set this width
