### ISSUE TITLE
Multiple columns end up in the first one (only for specific file)

### ISSUE THREAD

**Issue by jonalange** [janisdd/vscode-edit-csv#62]
### What OS?
- Mac

### Version?
- vs code plugin

### Description
So far everything is working and every csv I opened worked as expected. 
Just now I opened a file and it was completely messed up. The columns were shifted to the left and most of the columns got inserted into the first one and the following don't contain the content that they should contain.

The strange part is: Every csv is exported from our cms with the same settings and every csv is (besides the content) identical.
Every other csv with the same columns work. Just not this one.

I tried a random online csv converter and it displayed correctly. I also tried your only converter and the same bug comes up.
I think it's a really strange bug / edge case but I can't figure out what the problem could be (special characters or something like this).

It's really hard to explain, if tell me where I can send you the csv (without being public) I can send it to you.

### Steps to reproduce
If you have a way for me to send you my two files privately I can send you them for further investigation.

**Comment by jonalange** [comment]
Quick addition: Also the mac finder preview displays the table correctly.

**Comment by janisdd** [comment]
You can try to remove as much sensitive information as possible and send me an email: janisdd`-at-`web.de

**Comment by janisdd** [comment]
This is actually not a bug but intended ;) The one csv file contains 7x `;` and 10x `|` so papaparse auto guesses that `|` is the delimiter (which is a good guess syntax wise).

You can check which delimiter is used by expanding the read options and hover over the `?` behind the delimiter option.
After you set the right delimiter you need to click on `reset data and apply read options`.

If you only work with csv files that use `;` as separator, you can set the option `csv-edit.readOption_delimiter` (sets the initially used delimiter).

However, it bothers me that the after clicking `reset data and apply read options` the column sizes are kept (but in this case the columns changed). I guess I'll try adding a button to force auto resize the columns.

**Comment by janisdd** [comment]
Guess this can be closed
