### ISSUE TITLE
Text does not wrap when column is resized to be narrower than the text it contains.

### ISSUE THREAD

**Issue by motion-x86** [janisdd/vscode-edit-csv#7]
It somewhat wraps, but in a very weird way where a big portion of the wrapped string is invisible. This really hinders the ability to work with very large string values.

**Comment by janisdd** [comment]
From my testing wrapping never applied...
The reason for this is the `trimWhitespace:false` option in handsontable (a bug in handsontable).

I have created an issue for this https://github.com/handsontable/handsontable/issues/6232

**Comment by AMBudnik** [comment]
Hi guys. I just wanted to leave an update here (even when it's closed). We've just made an official fix https://github.com/handsontable/handsontable/issues/6232 and wanted to let you know. Sorry that it took so long. Now it will just get better.
