### ISSUE TITLE
Removing columns doesn't remove header

### ISSUE THREAD

**Issue by Matthanol** [janisdd/vscode-edit-csv#70]
### What OS?

- Windows

### Version?

- vs code plugin

### Description
When trying to remove a column the data is removed but the header is not, causing data to move to the wrong header and the column is not removed

### Expected behavior

Deleting a column deletes data and the header

### Steps to reproduce

Remove a column by clicking the icon in the header or right-click and remove column

**Comment by janisdd** [comment]
I can reproduce this... must have sneaked in with some of the latest updates. I'll look into this

**Comment by janisdd** [comment]
Should be fixed now... 
However, there is still an issue with undo/redo and reordering columns (this is an issue from handsontable, see #71)
