### ISSUE TITLE
Change Bulma css to VSCode Webview Ui Toolkit

### ISSUE THREAD

**Issue by janisdd** [janisdd/vscode-edit-csv#73]
### Version?
- both

### Feature

When microsoft releases a 1.x version of https://github.com/microsoft/vscode-webview-ui-toolkit we should probably use this in order to get a more "unified" look and feel with vs code.
Currently we use bulma css https://bulma.io/

Actually, we only need a few components from the ui/css libraries so the visual changes should be minimal

**Comment by niccolomineo** [comment]
I believe this extension has some pretty good potential and I also would love to see a style that is more coherent with VSCode.

**Comment by janisdd** [comment]
Pretty much done but there are some things to do:
- testing
- check if bulma extension is still needed

Also some notes about webview-ui-toolkit

- text field, text area
  - input events aren't triggered if some cell is selected (the cell gets the event/input)
  - this has probably something to do with the underlying framework https://github.com/microsoft/fast which uses some sort of proxy and re-emits events... somehow the table cell gets the key down event before the emit?
  - thus, normal input fields are used but styled as vs code text fields
- dropdown
  - font size cannot be changed (fixed to 13px?)

**Comment by niccolomineo** [comment]
Nice job. I wonder why the UI elements have to be so big, though?

**Comment by janisdd** [comment]
To be more easily to click/interact with. Another reason for the buttons is that they contain the small arrow buttons.

The icons and font in the top could be smaller maybe...

![Bildschirmfoto 2022-06-07 um 11 09 19](https://user-images.githubusercontent.com/12775963/172343738-2af4dc03-79c5-4b6d-bc06-5a1046d1f4c6.png)
![Bildschirmfoto 2022-06-07 um 11 09 35](https://user-images.githubusercontent.com/12775963/172343760-383e1969-fcae-4627-9835-7b9e795de754.png)
![Bildschirmfoto 2022-06-07 um 11 08 18](https://user-images.githubusercontent.com/12775963/172343767-828e7637-f399-42de-ac5b-416e6ed3c9db.png)

**Comment by niccolomineo** [comment]
I'd personally prefer having a UI that's consistent with VSCode. I can interact with the VSCode UI buttons without any issues, even though they're not large.

**Comment by janisdd** [comment]
As I said, the arrow buttons right to the add row and add column buttons also need space. The style is consistent now, if you zoom in vs code the size would match at some point.

Larger buttons are also better for the web (e.g. tablet) and maybe also for impaired people.

**Comment by janisdd** [comment]
Closing this for now.
