### ISSUE TITLE
control+tab not switching tabs when inside "edit csv" tab

### ISSUE THREAD

**Issue by overtomanu** [janisdd/vscode-edit-csv#76]
### What OS?
- Mac

### Version?
- vs code plugin

### Description
When inside edit csv tab, if i press ctrl+tab shortcut, it should switch to other tab, but instead its selecting next cell.

### Expected behavior

What you'd expect to happen.

### Steps to reproduce
open csv file, click on "edit csv", then press control+tab and observe the issue

**Comment by overtomanu** [comment]
i didnt see existing issue before logging this.
Might be related to issue #31

**Comment by janisdd** [comment]
I also think the root cause is the same as in #31. As the comment https://github.com/janisdd/vscode-edit-csv/issues/31#issuecomment-950240963 suggests `ctrl+tab` already, I think we can close this?

**Comment by overtomanu** [comment]
yes i am closing this. thank you for looking into this
