### ISSUE TITLE
CSV editing should occur in-place

### ISSUE THREAD

**Issue by niccolomineo** [janisdd/vscode-edit-csv#79]
I would like to suggest having the CSV editing tab open in place of the raw CSV file tab, in the VSCode plugin.

The CSV editing tab should therefore also feature a button to go back to the raw view.

**Comment by niccolomineo** [comment]
Hi, any progress on this?

**Comment by JackDjTom** [comment]
Adding a option to open csv-Files automatically in the editor tab would be fantastic.

**Comment by niccolomineo** [comment]
I am not using this extension anymore + I am not seeing advancements on this, so I am just closing this issue.
