### ISSUE TITLE
Double click column handle force width does not work

### ISSUE THREAD

**Issue by Nolkeg** [janisdd/vscode-edit-csv#8]

**Comment by janisdd** [comment]
It's working fine for me. Can you provide example data and steps to reproduce?
Do you have `Enable Wrapping` enabled?

**Comment by Nolkeg** [comment]
I have a 25 words lorem Ipsum in a column.
when I open the csv file with Edit csv, The column is auto adjusted to accumodate the long text.
Now, Instead of having to manually drage column for each column, I double click the column handle to shrink it to 200px. Nothing happened.
If I shrink the column manually then tried to double click the column handle, they will expand automatically to the size of the long text again.

my setting
enable wrapping = true
and that's it.

![image](https://user-images.githubusercontent.com/46750330/64916415-c79d5d00-d7a7-11e9-836d-874ed036fd85.png)
here, if I double click here it will just expand to full string length, not fixed 200px in my setting.

by the way, is there a way to set "maximum" column width? it would be great help since I wont have to adjust column size manually everytime I open a new csv file.

**Comment by janisdd** [comment]
Hmm... do you maybe slightly resized the column before double clicking? The fixed 200px is only applied if you click on the column handle if it has exactly the auto size (initial).
I could add a `+-X` tolerance to apply the fixed column width...

But I think your suggestion for an option to set the maximal (initial) column width would be better.
I'll have a look

**Comment by janisdd** [comment]
After some fiddling I added an option `initialColumnWidth` wich will let you set the initial column width. In conjunction with the `enableWrapping` option, it should be fine :)

**Comment by Nolkeg** [comment]
thank you so much <3
