### ISSUE TITLE
Cell when focused is not saved (after pressing CTRL+S) to the actual CSV file

### ISSUE THREAD

**Issue by mkloar** [janisdd/vscode-edit-csv#80]
### What OS?
- Windows

### Version?
- vs code plugin (v0.6.5)

### Description
While editing the column in the CSV and when column (or data) is focused, the editor then is not storing the column into the actual CSV file (after pressing CTRL+S keyboard combination).

### Expected behavior
When the column is focused and after pressing CTRL+S, the column should be stored in the actual CSV file.

### Steps to reproduce
1. Open VSCode
1. Open any CSV
2. Press "Edit csv" button in the upper right corner
3. Add Header columns (in my example: Code, Description, IsEnabled)
4. Add a column with the following data: A1	Some description	false (in edit mode)
![image](https://user-images.githubusercontent.com/17946736/155104649-3e67faa2-7a83-4fda-97c9-aad1fa4091b6.png)
5. After the final keystroke when writing the last column (false), stay with the mouse on this column and press CTRL+s
6. Column with data "false" in not stored to the actual CSV file (after pressing CTRL+s)
![image](https://user-images.githubusercontent.com/17946736/155105663-76bcee1e-a0fd-478d-9e26-63de8865aaea.png)

**GIF:**

![edit-csv-bug](https://user-images.githubusercontent.com/17946736/155111299-9cf826e9-0aed-4045-ae0c-2d82fd69e4d2.gif)

**Comment by janisdd** [comment]
Actually this is by design... you are still in cell-edit mode. You need to click into another cell, press tab/enter or something that changes the focused cell. If you press `esc` you can cancel the cell edit.

**Comment by janisdd** [comment]
Thinking about this again, it might be useful to have this to not unexpectedly lose changes. After pressing `ctrl/cmd+s` the cell editor should commit the change (https://handsontable.com/docs/6.2.2/tutorial-cell-editor.html).

This will ship with the next update.
