### ISSUE TITLE
About Column Display Error 

### ISSUE THREAD

**Issue by shio2345** [janisdd/vscode-edit-csv#82]
### What OS?
- Mac

### Version?
 1.64.2 (Universal)

### Description

When a csv file with 2000rows × 300column is opened, 300 elements are combined into one column.
The porpose is to get all  elements contained in each column using py program.

**Comment by janisdd** [comment]
Can you maybe post a picture of this? I've tested with 2000x301 and it works as expected.
![csv_2000x301](https://user-images.githubusercontent.com/12775963/156883203-d344000a-a111-4f3d-b561-7959c6b05486.png)

**Comment by shio2345** [comment]
As you can see in this picture, 1 column contain 300 elements.
The original data had 200,000 rows, but it was divided and reduced to 2,000 rows.
Could that be the cause of the error?

<img width="1440" alt="スクリーンショット 2022-03-05 22 23 27" src="https://user-images.githubusercontent.com/100994276/156884927-38f46677-2d44-43b5-bed9-a5c19c53fba9.png">

**Comment by janisdd** [comment]
Ah, I guess the delimiter was wrongly detected... Click on read options and check if it's the right delimiter (your data seems to use `,`). 
You can hover over the `?` next to the delimiter to check which one was detected.

**Comment by shio2345** [comment]
I checked and it was labeled "Empty auto detect (detected :,)"

**Comment by shio2345** [comment]
<img width="1440" alt="スクリーンショット 2022-03-05 23 05 53" src="https://user-images.githubusercontent.com/100994276/156886760-3bb59167-51d1-4ac8-805d-28279a5fa580.png">

**Comment by janisdd** [comment]
This is strange... could you provide the csv file (or a smaller version) that reproduces this?

**Comment by shio2345** [comment]
There may be a problem with the data, because it appears the same way when it opened in Excel.

[csv_check.csv](https://github.com/janisdd/vscode-edit-csv/files/8190861/csv_check.csv)

**Comment by janisdd** [comment]
I see. It appears the problem are the `"..."` in the start and end of the lines. Quotes are normally used in csv to escape data, e.g., `"cell 1, that has a comma", cell 2, cell 3`. The editor thinks ever line is one big escaped cell.

Also I recommend installing the rainbow csv extension. It will color the columns in the text view of the csv file. For your file is only shows one color because the whole line is one big cell.

**Comment by janisdd** [comment]
If you generate the data yourself and you want to process the csv further, maybe consider using a csv library that handles all the special cases (escapes, multi line cells, ...)

**Comment by shio2345** [comment]
Thanks to your answers, I was able to revise my improvements.
I will now try to solve the problem in a different way.
I appreciate your response
