### ISSUE TITLE
Open table in current line and not in first line

### ISSUE THREAD

**Issue by gerritgriebel** [janisdd/vscode-edit-csv#83]
### Version?
- plugin v0.6.6
- vscode 1.65.1

### Feature

Current workflow: 
- Search some text using global search
- click on found line in csv file
- editor opens, cursor is in line of found text
- click on "Edit csv"
- table opens with cursor in line 1
- Search again
- Find desired line in table

Desired workflow:
- Search some text using global search
- click on found line in csv file
- editor opens, cursor in line of found text
- click on "Edit csv"
- **table opens with cursor in same line as in csv**

PS: It may even work with positioning to correct column from text file

**Comment by gerritgriebel** [comment]
It doesn't really matter how to cursor got into a certain position in the CSV text file. Cursor position should be maintained when switching to table. The documentation of workflow was just to make clear, why it makes sense to maintain cursor position. In my workspace I have 391 CSV files, some have  more than 10k lines. Your plugin is very useful in dealing with them 👍🙏

**Comment by janisdd** [comment]
Well, knowing the use cases is interesting and useful.
If you would have only one csv file, you could use the search in the table view to get to the row/cell. So for a single csv file the benefit is not that huge (I guess).

After looking into this, it is a bit harder than expected, here are some reasons (also as documentation for me):

- we only get the data out of the csv string (via papaparse), no positional information
  - quotes from field escapes are missing, escaped quotes are collapsed
  - multi-line field values are collapsed into a single line
  - what about multi-char delimiters? what when we place the cursor inside the delimiter?
  - we collapse empty lines between rows
  - **Solution: extend papaparse to output positional information**
    - takes more memory and time to store and compute (should be ok)
- header option (if set to true)
  - we now have n-1 rows left (header row cannot be selected)
  - comment rows before header (in csv file) for are shown under the header row (in table)
    - selected row must be adjusted

- if csv file contains errors (missing quotes or smth.)
  - might mess up the selected cell

- reset data
  - should also set the selected cell (probably the user has scrolled by this point...)
  - also, the row count could change (when read options have changed)
- csv source file content changed -> auto reload
  - also re-apply selected cell? 

---

I'm still not sure if after the table has to be rerendered/reset (e.g. after `Read options > Reset data and apply read options` or if the source csv file changed) the initially selected cell (via cursor position from editor) should be selected or not.
I think currently always cell 1,1 is selected... probably not changing the selected cell is more desired.

**Comment by janisdd** [comment]
for docs: another caveat was the hide comments option

There will be a new option `openTableAtCursorPos` in the settings to disable selecting the cell.
I think this feature is so useful, it should be the default and users can disable it, if they don't need it.

It needs some more testing but should be published in the next days (hopefully).

**Comment by janisdd** [comment]
I plan to rename the modes for `openTableAndSelectCellAtCursorPos`...
- `initalOnly` becomes `initialOnly_correctRowAndColumn`
- new mode `initialOnly_correctRowAlwaysFirstColumn` which selects the correct row but always column one

The mode `initialOnly_correctRowAlwaysFirstColumn` will become the default as it feels more natural (at least for me), especially when working with smaller files as I always click at the "right editor area"  where no text is and this would always select the last cell...

@gerritgriebel You would have to manually change the setting `csv-edit.openTableAndSelectCellAtCursorPos` to `initialOnly_correctRowAndColumn` to keep the current behavior
