### ISSUE TITLE
How to open the large csv file

### ISSUE THREAD

**Issue by virgil0219** [janisdd/vscode-edit-csv#85]
### What OS?
- Mac

### Description

I loaded a csv file has about 800MG.  
Clicking on the 'edit csv' button resulted in the display of 'Open a csv file first to show the csv editor or file too large' . 
I want to know how many MGs will privent loading, or how do I change the size of the loadable.

Please let me know if you familiar with the setup for this function.

**Comment by janisdd** [comment]
As far as I know the limit is 50MB (or 300k lines or something). I'll add the 50MB limit to the dialog message. If you are interested you can check out the vs code issue nr. 31078 to track the progress on their end.

However, I wouldn't recommend using this extension with such large files... I usually test with a ~12MB file and it lags substantially. If you don't need the graphical table, you can give rainbow csv a try.
