### ISSUE TITLE
Pasting into single-cell when text contains new line character

### ISSUE THREAD

**Issue by Kadam-Tushar** [janisdd/vscode-edit-csv#87]
General behavior is when we paste some text which contains new lines character and then the text after newline character is added in the next row but what I want to do is add the whole text into a single cell. 
is there something can I do to get this behavior?

**Comment by janisdd** [comment]
If you need to do this only a few times, you can double click on the cell (or press F2) to enter edit mode and then paste the text.

Not sure if this is possible but maybe a new shortcut might be good here, something like `pasting + shift/alt`...
Or a new option with enabled this by default.

I'll look into this at some point.

**Comment by janisdd** [comment]
After trying this, there are some open questions.

Tabs mark columns in the texts (if you copy cells from excel like programs), e.g., 
```
c11   c12
c21   c22
```
would be pasted into 4 cells.

@Kadam-Tushar  What would be the correct behavior for this? 
Paste everything into one cell and keep the tabs? 
Replace the tabs with single whitespace?
Only paste into a single cell if it does not contain tabs?

**Comment by Kadam-Tushar** [comment]
@janisdd  
I guess currently when we paste something into a cell new row is created when we see a new-line character and data is added in the next column when we encounter tabs. 

So these characters are acting like row and column separators. For my use case - I want to paste everything into one cell and keep the tabs because I am pasting code snippets and I wish to maintain the meaning of tabs and newline characters in those code snippets. 

But in general, can we have the option to change the interpretation of both of these row and column separating characters while pasting?

**Comment by janisdd** [comment]
Ok, I guess a new option is the right way to go here.

**Comment by janisdd** [comment]
The new option will be named `pasteMode`. For your use case you should select `ignoreAllSeparators`.

After looking through the code, I have to "warn" you that pasting text will remove escaped quotes, i.e., `""abc""` becomes `"abc"`.

For docs: the data is processed normally via sheet.js and the selected `pasteMode` will only re-join the cells to get the desired behavior.
