### ISSUE TITLE
add configuration for 50MB limit

### ISSUE THREAD

**Issue by hjrb** [janisdd/vscode-edit-csv#88]
### Version?
- vs code plugin: 0.6.8

### Feature

Files with size > 50MB can not be loaded and there is also no option to set this limit. if you add a configuration option for this users could choose to try using the extension for larger files - at their own risk. 50MB is really not much.

**Comment by janisdd** [comment]
Unfortunately this is a limit of vs code, not the extension. You could try https://marketplace.visualstudio.com/items?itemName=mbehr1.vsc-lfs and check if this somehow enables files > 50MB...

Even if it works, the table/ui would lag substantially (even with ~10MB files).
