### ISSUE TITLE
Option to use the VS Code font family

### ISSUE THREAD

**Issue by wtjones** [janisdd/vscode-edit-csv#89]
### Version?
- vs code plugin 0.6.8

### Feature

Currently the extension is using a variable-width font. When editing data, it is helpful to have a monospace font. I don't see an option to change the font, so maybe just use my current settings.

**Comment by janisdd** [comment]
Good idea, will ship with the next update.

The option will be called `fontFamilyInTable`. You can select `sameAsCodeEditor` to use the same font as the code editor.

For the docs: the css variable from vs code is `--vscode-editor-font-family`
