### ISSUE TITLE
Option to append a new line to CSV when saving

### ISSUE THREAD

**Issue by gerritgriebel** [janisdd/vscode-edit-csv#91]
### Version?

* vs code plugin

### Feature

Currently last new line of CSV file is removed when saving. This may be the default behavior, but I'd like an option to always append a new line to last line, so that all lines have a newline.

**Comment by janisdd** [comment]
I think the built-in editor settings `files.insertFinalNewline` and `editor.renderFinalNewline` are more appropriate for that?

**Comment by gerritgriebel** [comment]
files.insertFinalNewline works perfectly. It absolutely ok, that vscode does this for any file, not just CSV. Thanks for the hint!
