### ISSUE TITLE
Option for disabling wrapping in navigation with arrow keys

### ISSUE THREAD

**Issue by gerritgriebel** [janisdd/vscode-edit-csv#92]
### Version?

- vs code plugin

### Feature

With large CSV tables, I use the arrow keys left/right to navigate the table. Accidently I often get to the next/previous line, if I hit left or right end of table. Same with up/down. Would be nice to able to disable this wrapping behavior by a setting.

**Comment by janisdd** [comment]
The options will be called `lastRowOrFirstRowNavigationBehavior` and `lastColumnOrFirstColumnNavigationBehavior` where you can select `stop` to disable wrapping

For the docs the handsontable setting: https://handsontable.com/docs/6.2.2/Options.html#autoWrapRow
