### ISSUE TITLE
default Fixed columns not working

### ISSUE THREAD

**Issue by thomasluxton** [janisdd/vscode-edit-csv#97]
### What OS?
Windows

### Description
Setting the Fixed Columns Left parameter in the settings doesn't seem to fix the first row. Manually adjusting the value in the gui, seems to re-enable the feature.
![image](https://user-images.githubusercontent.com/79663182/181287178-fd17ce30-ecdf-474f-b0d7-8b5701f06f1e.png)

### Expected behavior
When opening csvs that the first column is fixed by default

### Steps to reproduce
1. Edit the config, set the "Fixed columns Left" to 1
2. Open up a new csv file
3. note that the left column is not fixed.
4. adjust the fixed columns from 1 > 0 then 0 > 1 and note that the first column is now fixed.

**Comment by janisdd** [comment]
Can confirm this. However, this only occurs if the option `has header` is also enabled.
It also breaks if `has header` is manually toggled in the read options.

A fix will be shipped with the next update
