### ISSUE TITLE
Opening bigger files than 50 mb

### ISSUE THREAD

**Issue by MrGKanev** [janisdd/vscode-edit-csv#99]
### Version?
- vs code plugin v0.7.2
- browser 1.72.0
- Electron 19.0.17
- Chromium 102.0.5005.167

### Feature

I think there should be an option for opening bigger files than 50 MB if there isn't any code/software limitation stopping it.

**Comment by janisdd** [comment]
I fear this is limited by vs code itself, see #88 and this extension https://marketplace.visualstudio.com/items?itemName=mbehr1.vsc-lfs for some background info

**Comment by janisdd** [comment]
And see discussion https://github.com/janisdd/vscode-edit-csv/discussions/98
